[RFC] vim-patch:8.2.0953,8.2.0955,8.2.0956
neovim/neovim pull request #12955
Opened 2020-09-21 15:10 UTC by vigoux

#### vim-patch:8.2.0953: spell checking doesn't work for CamelCased words

Problem:    Spell checking doesn't work for CamelCased words.
Solution:   Add the "camel" value in the new option 'spelloptions'.
            (closes vim/vim#1235)
https://github.com/vim/vim/commit/362b44bd4aa87a2aef0f8fd5a28d68dd09a7d909

#### vim-patch:8.2.0955: build fails

Problem:    Build fails.
Solution:   Add missing struct change.
https://github.com/vim/vim/commit/215f49c4d720367be29f56168f363a0ee9eaf86b

#### vim-patch:8.2.0956: spell test fails

Problem:    Spell test fails.
Solution:   Add missing change the spell checking.
https://github.com/vim/vim/commit/e0ebeda4d8219a8955001b43ef7a9268452ef7f5

2020-09-23 05:07 UTC, vigoux commented
Appveyor fail seems unrelated.

2020-09-23 19:49 UTC, vigoux commented
@janlazo may I have your opinion on this ? This is my very first port...

2020-09-23 23:24 UTC, janlazo commented on runtime/doc/options.txt
> +			{not available when compiled without the |+syntax|
`+syntax` feature is always enabled.

2020-09-24 01:45 UTC, janlazo commented on src/nvim/spell.c
> +  int use_camel_case = *wp->w_s->b_p_spo != NUL;
bool

2020-09-24 01:46 UTC, janlazo commented on src/nvim/spell.c
> +  int camel_case = 0;
bool

2020-09-24 01:51 UTC, janlazo requested changes
LGTM aside from the minor issues.

2020-09-24 02:35 UTC, janlazo commented
Please port patch 8.2.1678 as well.

2020-09-24 05:18 UTC, vigoux commented
All comments adressed, @janlazo may I ask you to review again ?

2020-09-24 05:23 UTC, janlazo approved these changes

2020-09-24 05:24 UTC, janlazo commented on src/nvim/spell.c
> +  bool camel_case = 0;
false

2020-09-24 06:09 UTC, vigoux commented on src/nvim/spell.c
> +  bool camel_case = 0;
Lol I am so lazy sometimes...

2020-09-24 07:10 UTC, merged

2020-09-24 07:57 UTC, bluz71 commented
@vigoux,

I just tested the latest Neovim `master` branch, the new `set spelloptions=camel` options works great.

Thank you very much.

Best regards.