docs: Edit man.vim's help entry.
neovim/neovim pull request #13394
Opened 2020-11-27 00:50 UTC by shade-of-noon

Here I
- Moved the paragraphs so that the related information is closer together (easier to grok).
- Added vertical spacing between descriptions to make it easier to read (and also for consistency with other help pages).
- Changed the indentation from spaces to tabs for consistency with the rest of the file and other help files.

Closes #13360

2021-02-11 02:09 UTC, janlazo commented
cc @nhooyr

2022-04-07 11:09 UTC, dundargoc commented
I have also mailed nhooyr. Not sure what what more could be done except go full Liam Neeson and track him down.

2022-04-09 09:11 UTC, clason requested changes

2022-04-09 09:11 UTC, clason commented on runtime/doc/filetype.txt
> +navigation.  Also see |find-manpage|.
We don't do double-spacing in our docs (at least not consistently, and certainly not for new docs!)

2022-04-09 09:11 UTC, clason commented on runtime/doc/filetype.txt
> +			for relative paths.
Please keep indentation consistent.

2022-04-09 09:11 UTC, clason commented on runtime/doc/filetype.txt
> +			Equivalent to ":set filetype=man".
Backticks for code snippets (here and elsewhere).

2022-04-09 09:11 UTC, clason commented on runtime/doc/filetype.txt
> +b:man_default_sects	Comma-separated, ordered list of preferred sections.
Why did you remove the tags?

2022-12-17 01:57 UTC, closed without merging