LSP: progress callback should only update existing dict for reports
neovim/neovim pull request #13652
Opened 2020-12-31 19:24 UTC by jdrouhard

This was causing the title to disappear when report messages were received.

This also provides a fix for the error message when an end message doesn't have an associated begin.

2020-12-31 21:02 UTC, mjlbach requested changes
@teto 

The main thing this PR does, is to change the update of the `client.messages.progress` table to overwrite only the percentage and message properties on $report, I think this part is correct, since previously we were overwriting the table which meant `client.messages.progress[token].message.title` was wiped on report.
```lua
 client.messages.progress[token].message = val.message;
 client.messages.progress[token].percentage = val.percentage;
```
I disagree with standardizing on reporting the client name as it is non-unique across multiple of the same instances of the language server.

2020-12-31 21:06 UTC, jdrouhard commented on runtime/lua/vim/lsp/handlers.lua
> +    err_message("LSP[", client_name, "] client has shut down after sending the message")
This is the same format the other error logs are written with in the various handlers. I think it's best to keep the error message styling consistent. If you think the client ID should always be there, then I recommend we change all calls to `err_message` in the file accordingly to match in a separate PR.

2020-12-31 21:09 UTC, mjlbach commented on runtime/lua/vim/lsp/handlers.lua
> +    err_message("LSP[", client_name, "] client has shut down after sending the message")
Yeah, teto's call, otherwise LGTM

2021-01-01 22:51 UTC, merged

2021-01-01 22:59 UTC, mjlbach commented on runtime/lua/vim/lsp/handlers.lua
> +    err_message("LSP[", client_name, "] client has shut down after sending the message")
This is dead code, I will fix in another PR, but in the cases where`if not client` is true, triggering the error handler, client_name will always equal string.format("id=%d", client_id)

2021-01-01 23:00 UTC, jdrouhard commented on runtime/lua/vim/lsp/handlers.lua
> +    err_message("LSP[", client_name, "] client has shut down after sending the message")
Good point! Thanks, missed that.