Add Termdebug disassembly window
neovim/neovim pull request #13660
Opened 2021-01-01 20:42 UTC by mikesart

:Asm should bring up disassembly window

or setting:

  g:termdebug_disasm_window

Values greater than 1 will set disasm window height.

Code works by calling gdb disassemble command, demangling output and
storing in Termdebug-asm-listing buffer + window.

Current pc address is parsed from 'addr=' cursor msg and we search for
that address in the disasm window. When the search fails, we execute a
new "disassemble $pc" command.

When in a location without a proper stack frame, "disassemble $pc" can
fail and in this case we add a +length argument and try again.

Tested with x86_64 gdb v10.1 and v8.2.1, and aarch64 gdb v7.12.

2021-01-01 20:51 UTC, bfredl commented
just so we know: is this ported from vim or is it new neovim-specific work?

2021-01-01 20:54 UTC, mikesart commented
> just so we know: is this ported from vim or is it new neovim-specific work?

I wrote all this myself (first foray into vimscript), and have only done this work for neovim since that's the editor I use and from what I can tell, the latest vim / neovim termdebug.vim files are quite different.

2021-01-01 21:05 UTC, mikesart commented
For reference, I added similar functionality to cgdb (all C code) several years ago:

https://github.com/cgdb/cgdb/commit/2b42e70d656a2fdbc931ee46a449221023a94890

I like neovim + termdebug better (as it's integrated into my main editor), but I oftentimes can't debug w/o disassembly. Hence this patch. :) Thanks!

2021-01-02 20:33 UTC, chrisbra commented
can you please send this against vim/vim?

2021-01-03 00:05 UTC, mikesart commented
> can you please send this against vim/vim?

https://github.com/vim/vim/pull/7605

Thanks Chris.

2021-02-13 21:35 UTC, janlazo commented
Format the commit message, similar to the commits in https://github.com/neovim/neovim/pull/13835.  https://github.com/vim/vim/commit/82be4849eed0b8fbee45bc8da99b685ec89af59a includes your changes.

2021-02-14 00:58 UTC, mikesart commented
> Format the commit message, similar to the commits in #13835.

Apologies, but I'm looking at 13835 and in the 6 commits I only see messages like:

> runtime/zsh: 23515b4ef7580af8b9d3b964a558ab2007cacda5
> port zsh compiler only 

So I assume you're saying something like this?

> runtime/termdebug 82be4849eed0b8fbee45bc8da99b685ec89af59a
> port termdebug dissasembly window only

Thanks.

2021-02-14 14:33 UTC, janlazo commented
Yes.
You can add more context so that it is clear which files were ported and why.

2021-03-10 01:02 UTC, janlazo commented
Documentation for ` g:termdebug_disasm_window` is missing. Port the changes from Vim `runtime/doc/terminal.txt` to `runtime/doc/nvim_terminal_emulator.txt`.

2021-03-10 01:04 UTC, janlazo requested changes
I will merge this to 0.5 if the Temdebug documentation from the same vim patch is ported to Neovim.

2021-03-10 03:18 UTC, mikesart commented
Should be updated. Thanks.

2021-03-10 13:20 UTC, merged