lsp: Expose handler of execute_command()
neovim/neovim pull request #14546
Opened 2021-05-13 15:30 UTC by mickael-menu

The [LSP specification](https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand) states that `workspace/executeCommand` can return an arbitrary response (`any | null`). This change exposes the `handler` parameter to let users retrieve any command result.

I tested this change with an LSP server sending a result when calling `workspace/executeCommand`.

2021-05-14 04:31 UTC, mjlbach commented
Documentation is auto-generated from the function comments, but otherwise this looks good to me. @mfussenegger?

2021-05-14 04:31 UTC, mjlbach requested changes
I would remove the changes in lsp.txt. We should re-run docgen before 0.5 is cut.

2021-05-14 07:52 UTC, mickael-menu commented
@mjlbach Thanks, I removed the doc changes.

2021-05-14 07:57 UTC, mjlbach approved these changes

2021-05-14 08:48 UTC, mfussenegger commented
I see how this is useful and I kinda wanted to have something like this myself as well from time to time, but I'm also a bit reluctant because it breaks the symmetry of the `.buf` / `.handlers` functions.

Why is `execute_command` the only method that takes the handler argument? Given that `vim.lsp.buf_request(0, `workspace/executeCommand`, ...)` is not much harder to call I'm not certain the little bit of convenience is worth deriving from the general pattern.

So -0/+0 from my side.

2021-05-14 08:55 UTC, mjlbach commented
Yeah I remember that convo with TJ on your other PR... I won't merge until @tjdevries gives his thoughts because we keep coming up against this issue and it seems like people want this pattern

2021-05-14 09:07 UTC, mickael-menu commented
> Why is `execute_command` the only method that takes the handler argument?

I think `workspace/executeCommand` is a bit special since it is used for extensions in LSP servers. For almost all other methods it's reasonable to expect a single way to handle it. But here the handler really depends on which command is called. 

> Given that `vim.lsp.buf_request(0, 'workspace/executeCommand', ...)` is not much harder to call I'm not certain the little bit of convenience is worth deriving from the general pattern.

Yes this is actually how I implemented it in my own config, but it breaks the symmetry on the client side. Here's an example, I have a command not returning anything and another one with a result:

```lua
configs.zk.index = function()
  vim.lsp.buf.execute_command({
    command = "zk.index",
    arguments = {vim.api.nvim_buf_get_name(0)},
  })
end

configs.zk.new = function(...)
  vim.lsp.buf_request(0, 'workspace/executeCommand',
    {
        command = "zk.new",
        arguments = {
            vim.api.nvim_buf_get_name(0),
            ...
        },
    },
    function(_, _, result)
      if not (result and result.path) then return end
      vim.cmd("edit " .. result.path)
    end
  )
end
```

That being said, maybe a way to follow more closely the `buf`/`handlers` segregation could be to enable per-command handlers. For example:

```lua
vim.lsp.handlers["workspace/executeCommand/zk.new"] = function(_, _, result)
  if not (result and result.path) then return end
  vim.cmd("edit " .. result.path)
end
```

2021-05-14 18:43 UTC, mjlbach commented
I think I'm inclined to agree with @mfussenegger after talking on matrix. Summarized:

```
I'd be inclined to leave it as it is. vim.lsp.buf_request(0, 'workspace/executeCommand', command, handler) isn't that much harder to call than vim.lsp.buf.execute_command(command, handler)
```

2021-05-14 21:17 UTC, mickael-menu commented
I took a look at your conversation on matrix. What I'm doing is closer to plugin development or an `nvim-lspconfig` pre-made config than simple user keybindings, so I guess I can get by with the `buf_request()` workaround if you prefer to leave it that way.

Thanks for considering this change anyway.

@mjlbach I'll jump on the opportunity to ask if the kind of stuff I do would be welcome on `nvim-lspconfig`? Unlike most LSP servers I'm not exposing a programming language's features. My plugin mostly augments Markdown with workspace-level features.

2021-05-14 21:17 UTC, closed without merging

2021-05-14 23:32 UTC, mjlbach commented
@mickael-menu nvim-lspconfig is generally supposed to be the minimal configuration necesary to enable all lsp spec compliant features of a language server. That being said, for servers which expose 1-2 custom protocols I've generally agreed we can just add handlers/extra commands for those as well. As the config grows, I generally recommend splitting it off into its own plugin (like nvim-jdtls or nvim-metals, although those were *not* split off from nvim-lspconfig)

2021-05-15 12:04 UTC, mickael-menu commented
@mjlbach Thanks for your input, from what you described I think it makes more sense in its own plugin.