LSP: Add bufnr to formatting request
neovim/neovim pull request #14641
Opened 2021-05-26 04:22 UTC by lukas-reineke

Send the buffer number to the `textDocument/formatting` LSP request, so that the handler gets it on the return.
The build in formatting handler does not use the buffer number. But user provided one's might want to use it.

2021-06-12 12:18 UTC, mfussenegger approved these changes

2021-06-12 13:11 UTC, disrupted requested changes
Thanks for the fix! Please also apply it to `formatting_sync`.

2021-06-14 22:03 UTC, mjlbach commented
@lukas-reineke after you add to formatting_sync, I'll merge.

2021-06-16 00:30 UTC, lukas-reineke commented
updated `formatting_sync` and `formatting_seq_sync` as well

2021-06-16 06:53 UTC, merged