Fix match finding halting if you type too fast (issue #15189)
neovim/neovim pull request #15190
Opened 2021-07-25 18:46 UTC by AndyGozas

2021-07-27 09:28 UTC, vigoux requested changes

2021-07-27 09:28 UTC, vigoux commented on src/nvim/edit.c
> +  int looped_around = 0;
This should be a boolean.

2021-07-27 11:43 UTC, AndyGozas commented on src/nvim/edit.c
> +  int looped_around = 0;
Sure, done!

2021-09-07 10:55 UTC, clason commented
If this is a vim patch, please use the (mandatory!) commit message format for those; see, e.g., https://github.com/neovim/neovim/pull/15449

2021-09-17 17:04 UTC, closed without merging