vim-patch 8.2.2938: after using motion force from feedkeys() it sticks
neovim/neovim pull request #15240
Opened 2021-08-02 09:20 UTC by xiaopeng-ye

Problem:   After using motion force from feedkeys() it may not be reset.
Solution:   Clear motion_force in clearop().

issue: https://github.com/vim/vim/issues/8323
vim-patch:https://github.com/vim/vim/commit/21492743e80c6740bac65a91311c28bede8ef2f8

2021-08-02 19:30 UTC, janlazo commented
Test is missing.

2021-08-02 23:25 UTC, janlazo commented
Cannot review. Commit should start with `vim-patch:8.2.2938`. Missing `:`.

2021-08-03 02:46 UTC, janlazo commented
The commit message is not the same as what vim-patch.sh generates.

```
$ ./scripts/vim-patch.sh -r 15240

Downloading data for pull request #15240.
Found 1 commit(s).

✔ Detected Vim patch '8.2.2938'.

Creating files.
✔ Saved pull request diff to '/home/jan/repo/git/neovim/nvim-8.2.2938.patch'.
✘ Wrong commit message.
  Expected:
vim-patch:8.2.2938: after using motion force from feedkeys() it sticks

Problem:    After using motion force from feedkeys() it may not be reset.
Solution:   Clear motion_force in clearop(). (closes vim/vim#8323)
https://github.com/vim/vim/commit/21492743e80c6740bac65a91311c28bede8ef2f8
  Actual:
vim-patch:8.2.2938: after using motion force from feedkeys() it sticks
```

2021-08-15 22:49 UTC, janlazo commented on src/nvim/testdir/test_visual.vim
> +    onoremap <expr> i- execute('let g:mode = mode(1)')->slice(0, 0)
Method syntax was not ported into master branch yet.

2021-08-15 22:50 UTC, janlazo requested changes
Fix the failing test or wait for the method syntax to be ported.

2021-08-15 22:50 UTC, janlazo commented on src/nvim/testdir/test_visual.vim
> +    onoremap <expr> i- execute('let g:mode = mode(1)')->slice(0, 0)
```
Executed:  2023 Tests
 Skipped:   181 Tests
  FAILED:     1 Tests


Failures: 
	From test_visual.vim:
	Found errors in Test_visual_force_motion_feedkeys():
	Caught exception in Test_visual_force_motion_feedkeys(): Vim(call):E15: Invalid expression: >slice(0, 0) @ function RunTheTest[37]..Test_visual_force_motion_feedkeys, line 2
```

2021-08-15 22:51 UTC, janlazo commented on src/nvim/testdir/test_visual.vim
> +    onoremap <expr> i- execute('let g:mode = mode(1)')->slice(0, 0)
```
Executed:  2023 Tests
 Skipped:   181 Tests
  FAILED:     1 Tests


Failures: 
	From test_visual.vim:
	Found errors in Test_visual_force_motion_feedkeys():
	Caught exception in Test_visual_force_motion_feedkeys(): Vim(call):E15: Invalid expression: >slice(0, 0) @ function RunTheTest[37]..Test_visual_force_motion_feedkeys, line 2
```

2021-08-29 09:53 UTC, pierreganty commented
@xiaopeng-ye has rewritten the test without using `slice()`. @janlazo could you have a look at it again, please ?

2021-08-29 20:24 UTC, janlazo approved these changes
LGTM

Not sure what `->slice(0,0)` is for in the vim patch. Vim does not need it to pass the test.

2021-08-29 21:08 UTC, merged