Signal autocmd: support SIGWINCH
neovim/neovim pull request #16030
Opened 2021-10-14 22:02 UTC by will

When my OS (macos) switches from light mode to dark mode automatically my editor (iterm2) will now switch colorschemes automatically and send `SIGWINCH` to any process that is currently running. 

I'd like to add an autocmmand for when neovim receives `SIGWINCH`, that way I can decide myself if the winch is because of resizing or because of the outside colorscheme changing and I can swap the background mode of my nvim theme myself if the latter.

I have it sort of working: 

https://user-images.githubusercontent.com/1973/137401558-1a84e119-f419-4564-89ad-49a717935be8.mp4

But it does sometimes crash neovim, so I think something is wrong. If someone can help me get on the right track, I can add tests and make this a proper PR.

Thanks for consideration.

2021-10-15 15:22 UTC, erw7 requested changes

2021-10-16 09:05 UTC, erw7 commented
> I tried to add a test for this in test/functional/autocmd/signal_spec.lua, however simply following the pattern there does not work. I think this is because the signal handler is not registered in the tests. I'm not sure what the correct approach is.

The neovim under test does not have a TUI because it was started with `--headless` as a command line argument. Therefore, it does not have a handler for `SIGWINCH`. If you want to create a test, I think `functional/terminal/tui_spec.lua` is appropriate.

2021-10-16 09:19 UTC, erw7 commented
In the current implementation, the background color is redetected after `autocmd` is triggered by `SIGWINCH`. It's probably not the behavior you want. You may need to be a little more creative. However, if it becomes too complex, it will be difficult for this PR to be merged into master.

I gave you some technical advice, but I am skeptical about the need for this PR which is only available on Mac OS iterm2.

2022-04-10 22:54 UTC, justinmk commented
see #18029

2022-04-10 22:54 UTC, closed without merging