vim-patch:8.2.{3933,3793,3978,4013,4032,4048}
neovim/neovim pull request #17068
Opened 2022-01-13 06:51 UTC by VVKot

Problem:    After ":cd" fails ":cd -" is incorrect.
Solution:   Set the previous directory only after successfully changing
            directory. (Richard Doty, closes vim/vim#9419, closes vim/vim#8983)
https://github.com/vim/vim/commit/3d0abad5bf4fe125e219f1b56c4e8200cb900e2a

I skipped whitespace changes to `cursor_*` functions because the related patch is not ported yet, and we should not have problems with whitespace in the first place. Also, Neovim produces a different error code because we haven't ported https://github.com/vim/vim/commit/5fd0f5052f9a312bb4cfe7b4176b1211d45127ee yet. Should I mark patch as partial based on that?

The other patches are ifdef tweaking and language-specific, hence N/A.

2022-01-13 06:58 UTC, zeertzjq commented
Isn't the different error code because <https://github.com/vim/vim/commit/9b7bf9e98f06ece595fed7a3ff53ecce89797a53> was not ported yet?

2022-01-29 17:56 UTC, seandewar requested changes

2022-01-29 17:56 UTC, seandewar commented on src/nvim/testdir/test_cd.vim
> +  call assert_fails('cd /nonexistent', 'E472:')
```suggestion
  " v8.2.1183 is not ported yet
  " call assert_fails('cd /nonexistent', 'E344:')
  call assert_fails('cd /nonexistent', 'E472:')
```

Keep the original line, but comment it out with a message.

2022-01-30 11:26 UTC, VVKot commented
@seandewar I added that as separate commit - should I squash instead?

2022-01-30 23:59 UTC, seandewar commented
Yes it should be squashed :+1:

2022-01-31 00:11 UTC, seandewar approved these changes

2022-01-31 00:42 UTC, merged