build(deps): bump tree-sitter
neovim/neovim pull request #17130
Opened 2022-01-17 22:14 UTC by clason

update tree-sitter to https://github.com/tree-sitter/tree-sitter/commit/aaf4572727ac555766f9b60b34b231f8cd819859,
which includes a massive performance improvement to query construction (bumping ABI to 14, so this is breaking; parsers need to be reinstalled from grammar).

@neovim/treesitter @theHamsta

2022-01-17 22:59 UTC, theHamsta commented
![image](https://user-images.githubusercontent.com/7189118/149845615-f1b76c0c-bbdd-45fe-b430-6da928d060bb.png)

2022-01-17 23:19 UTC, theHamsta commented
Probably we should try to move workflows for optional binary distributions via GH workflows forward or our own CI f. Not all parsers will be ABI=14 from the beginning. But probably those who have problems with loading time which are those that matter.

2022-01-17 23:28 UTC, alex-pinkus commented
I think you probably want to wait for https://github.com/tree-sitter/tree-sitter/pull/1599 for this as well, since I see some minor tweaks to `TSLanguage` field names in that PR. With that change, tree-sitter will _understand_ parsers that have ABI=14 but not yet _generate_ them unless you explicitly ask for it.

2022-01-17 23:36 UTC, theHamsta commented
Right now nvim seems to segfault on my machine with the new version although I really tried to delete all dependency and build artifacts. Right on language load of a version 13 parser. It might also come from a system dependency that is different (language does not really matter in that regard 

![image](https://user-images.githubusercontent.com/7189118/149847745-1329832c-df26-4108-8a11-7e6534b6b1b2.png)

2022-01-17 23:59 UTC, theHamsta commented
```
set(TREESITTER_URL https://github.com/tree-sitter/tree-sitter/archive/691469c7833068225aed48ef66b1fb4eb6f9eb38.tar.gz)
set(TREESITTER_SHA256 c36efb458971ad48cfff0148cc29fce7579a54c655495063c597f23bca6bda42)
```

2022-01-18 01:27 UTC, alex-pinkus commented
Ugh, that segfault is because I made a silly mistake... see https://github.com/tree-sitter/tree-sitter/pull/1601

2022-01-18 06:57 UTC, vigoux requested changes
I think we should bump that to the latest commit.
It is great that this time we can anticipate the ABI change...

2022-01-18 08:08 UTC, clason commented
Yep, saw it; updated!

2022-01-18 08:58 UTC, vigoux approved these changes

2022-01-19 04:07 UTC, alex-pinkus commented
These test failures on the most recent version don't seem related to the perf changes; [on MacOS](https://github.com/neovim/neovim/runs/4850297254?check_suite_focus=true#step:10:8231):
```
  [  ERROR   ] test/functional/terminal/channel_spec.lua @ 21: associated channel is closed and later freed for terminal opened by termopen(), exited, and deleted by pressing a key
  test/helpers.lua:73: Expected objects to be the same.
  Passed in:
  (string) 'Vim(call):Can't send data to closed stream'
  Expected:
  (string) 'Vim(call):E900: Invalid channel id'
```


[On Windows](https://github.com/neovim/neovim/runs/4850297433?check_suite_focus=true#step:4:11362):
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/nvim/CMakeFiles/nvim.dir/message.c.obj: in function `mch_errmsg':
D:/a/neovim/neovim/src/nvim/message.c:2946: undefined reference to `libintl_fwprintf'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/nvim/CMakeFiles/nvim.dir/message.c.obj: in function `mch_msg':
D:/a/neovim/neovim/src/nvim/message.c:2960: undefined reference to `libintl_wprintf'
```

Let me know if there's any info I can provide to help debug.

2022-01-19 07:45 UTC, clason commented
@alex-pinkus Yeah, these test failures are not related to the PR; we've had to deal with flaky tests in general for a while. This PR is fine, we are just discussing how to best deal with the ABI change downstream before pulling the trigger.

2022-01-19 08:24 UTC, merged