Update to LibvtermCMakeLists.txt
neovim/neovim pull request #17519
Opened 2022-02-25 08:29 UTC by Fuzzier

Comment out the target `vterm-shared`, so Ninja will not abort due to multiple rules to generate `vterm.lib`, and Microsoft Visual Studio can build `vterm.lib` under Windows operation system.

2022-02-25 18:58 UTC, jamessan requested changes

2022-02-25 18:58 UTC, jamessan commented on third-party/cmake/LibvtermCMakeLists.txt
> +# add_library(vterm-shared SHARED ${VTERM_SOURCES} ${TBL_FILES_HEADERS})
Rather than commenting it out, just delete it.

2022-02-25 18:59 UTC, jamessan commented
Please also address the commit lint failure when updating your PR:

Invalid commit message: "Update LibvtermCMakeLists.txt"
    Commit: c32221c8c8a257a5bf14a6c82e67c2b3d5723ca9
    Commit message does not include colons.
    See also:
        [master/CONTRIBUTING.md#commit-messages](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#commit-messages)
        [conventionalcommits.org/en/v1.0.0](https://www.conventionalcommits.org/en/v1.0.0/)

2022-03-01 01:23 UTC, closed without merging

2022-03-01 08:00 UTC, clason commented
Why did you close this PR?

2022-03-01 10:12 UTC, Fuzzier commented
Sorry, I did not know how to correct it, so I made another PR.

2022-03-01 10:13 UTC, clason commented
You could have either amended your commit (`git commit --amend`, edit the commit message, and `git push -f`) or added a fixup commit that we would squash on merging. (The first option is better.)