docs(api): improve section on nvim_set_hl
neovim/neovim pull request #17692
Opened 2022-03-12 15:48 UTC by adrian5

2022-03-12 15:54 UTC, clason commented
Thank you, but these docs are autogenerated from the docstring in the code -- so any improvements must be made to the latter, or they will just get overwritten again.

(Personally, I don't actually see much improvement in your changes -- the markup is needed for `:help`.)

2022-03-12 16:11 UTC, adrian5 commented
I see, then I'll remove the first part. Is the commit still `docs(api)` in that case?

> Personally, I don't actually see much improvement in your changes

Well, aside from having multiple typos in that tiny section, I think the formatting made it hard to read (compared to neighboring functions). The `cterm` explanation also seemed more confusing than helpful.

> the markup is needed for `:help`

You mean `ctermfg`: vs plain cterm in the parameter list? I removed those to match the formatting used in the surrounding functions, as it looked more readable that way. But if it's important for functionality, I can add it back in.

2022-03-12 16:16 UTC, clason commented
> I see, then I'll remove the first part. Is the commit still docs(api) in that case?

You don't have to remove it, but it must be consistent. Yes, it's still about docs.

> Well, aside from having multiple typos in that tiny section, I think the formatting made it hard to read (compared to neighboring functions). The cterm explanation also seemed more confusing than helpful.

Sure, that's an an improvement -- although I don't quite agree about the changes. I do think the reference to `hi default` is useful here, and the new wording for `cterm` could be misunderstood: "sharing" means a bidirectional link, so setting `cterm` would change `gui` as well. Maybe "attributes default to those set for `gui` if not set"?

2022-03-12 16:31 UTC, gpanders requested changes
Thanks for the PR! Doc improvements are always welcome.

I added a few of my own suggestions.

2022-03-12 16:31 UTC, gpanders commented on runtime/doc/api.txt
>                               `:highlight` ) namespace.
```suggestion
                    {ns_id}  Namespace id for this highlight |nvim_create_namespace()|. 
                             Use 0 to set a highlight group globally |:highlight|.
```

2022-03-12 16:31 UTC, gpanders commented on runtime/doc/api.txt
> +                    {val}    Highlight definition map, like |synIDattr|. In
```suggestion
                    {val}    Highlight definition map, like |synIDattr()|. In
```

2022-03-12 16:31 UTC, gpanders commented on runtime/doc/api.txt
> +                             • default: Don't override existing definition
```suggestion
                             • default: Don't override existing definition |:hi-default|
```

2022-03-12 16:31 UTC, gpanders commented on runtime/doc/api.txt
> +                             • ctermbg: Sets background of cterm color
```suggestion
                             • ctermfg: Sets foreground of cterm color |highlight-ctermfg|
                             • ctermbg: Sets background of cterm color |highlight-ctermbg|
```

2022-03-12 16:41 UTC, adrian5 commented
> `cterm`  : cterm attribute map. sets attributed for
>                cterm colors. similer to `hi cterm`

I meant the first part being "confusing", doesn't `cterm` solely affect text properties such as boldness?

As for the second part, I didn't understand what it was pointing at. `hi cterm` alone is not a working command, so was this about how it's used similar to `cterm` in e.g. `hi GroupName cterm=…`?

> I do think the reference to `hi default` is useful here

Right, my bad. I think I got mixed up with `hi cterm` after purging that.

> and the new wording for cterm could be misunderstood: "sharing" means a bidirectional link, so setting cterm would change gui as well. Maybe "attributes default to those set for gui if not set"?

Agreed, I'm not happy with that wording either. Your sentence seems unambiguous.

2022-03-12 16:44 UTC, clason commented
> As for the second part, I didn't understand what it was pointing at. hi cterm alone is not a working command, so was this about how it's similar in use to cterm in e.g. hi GroupName cterm=…?

Agreed, that's not as clear as it should be. Yes, this is exactly about the `cterm=...` attributes.

2022-03-12 16:47 UTC, adrian5 commented
@gpanders Those are really good. I'm not familiar with the GitHub UI, can I just merge these into my commit via the buttons? Do they need to be squashed afterwards?

2022-03-12 16:49 UTC, clason commented
Yes, and yes. (Commit lint won't be happy otherwise.)

2022-03-12 17:05 UTC, adrian5 commented
Ok, great. I'll take of that later when I get home.

2022-03-13 09:41 UTC, adrian5 commented
I've merged the suggested changes and transferred them to the source docstring. I think this is a real improvement for the reader. I hope the changes are in order now.

2022-03-13 09:57 UTC, clason approved these changes

2022-03-13 12:41 UTC, gpanders approved these changes

2022-03-13 12:42 UTC, merged