feat(remote): add wait subcommands
neovim/neovim pull request #17856
Opened 2022-03-25 18:55 UTC by groves

This still needs more tests and handling of waiting for multiple edits. I was hoping to get some feedback on the approach in general as I work on those pieces.

2022-03-25 18:55 UTC, groves commented on runtime/lua/vim/_editor.lua
> +    vim.api.nvim_create_autocmd('BufUnload', {callback=function()
I'll need to wait till all the open bufs are unloaded, not just the first one.

2022-03-25 18:58 UTC, groves commented on runtime/lua/vim/_editor.lua
> +    local remote_chan_id = vim.fn.rpcrequest(rcid, 'nvim_get_api_info')[1]
This is a silly way to get the channel id for the remote side to callback with. I couldn't see a way to do that from the remote side though. Is there a way from inside an RPC to get the channel id for the other side of the connection? If not, would it make sense for me to add that?

2022-03-25 23:56 UTC, Shougo commented
I have tested the feature as git commit editor with neovim terminal, but neovim is launched within neovim terminal.
I like neovim-remote behavior instead.  It is possible?

2022-03-25 23:58 UTC, zeertzjq commented
Maybe this can be used:
```
nvim --server $NVIM_LISTEN_ADDRESS --remote-tab
```

2022-03-26 00:17 UTC, Shougo commented
I use it, but it launches within neovim terminal...

2022-03-28 13:59 UTC, groves commented
@Shougo Thanks for trying it out! Is the failure a regression with this PR, or is it failing with just the code on master? If it's failing on master, would you mind opening an issue, answering the below questions, and tagging me? I'd like to keep this PR focussed on changes in the PR.

In either case, a few more pieces of info would be helpful for me looking into this:
1. how are you launching the Neovim server instance with the terminal in it?
2. what command are you using as editor for git commit? How are you configuring git?
3. what do you mean by it being "launched in the neovim terminal"? That it's a new instance of neovim started in the terminal, or that it's' a split in the terminal window?
4. are there any error messages given? Is there anything in `:messages` in either the client or the server?

2022-03-29 00:37 UTC, Shougo commented
> Thanks for trying it out! Is the failure a regression with this PR, or is it failing with just the code on master? If it's failing on master, would you mind opening an issue, answering the below questions, and tagging me? I'd like to keep this PR focussed on changes in the PR.

I have tested the PR.  Because in master wait feature is not implemented yet.

I have tested it with neovim built in terminal.

I have set `$EDITOR` to `nvim --server {servername} --remote-tab-wait-silent` or `nvr --remote-tab-wait-silent`.
I have tested the editor by `git commit` command.

When `nvr`, the editor is neovim current tab(not terminal).  It is my expected behavior.
When the PR, the editor is executed in terminal in vim.  It is not expected result.

Note:  I have tested it in Alacritty terminal.  But I think it is same with neovim GUI client.

2022-03-29 00:38 UTC, Shougo commented
Note:  I use `nvim --listen ~/.cache/nvim/server.pipe` from terminal.

2022-03-29 00:40 UTC, Shougo commented
> what do you mean by it being "launched in the neovim terminal"? That it's a new instance of neovim started in the terminal, or that it's' a split in the terminal window?

It seems new instance in the terminal.  But you can test it easily.

> are there any error messages given? Is there anything in :messages in either the client or the server?

No error messages.  I think it is not error.

2022-03-30 00:44 UTC, Shougo commented
> What are you setting {servername} to in your nvim --server {servername} --remote-tab-wait-silent example?

I use `nvim --listen ~/.cache/nvim/server.pipe` from terminal.
I think the server feature works.  But it is not I expected...

> Also, using silent is going to suppress any warning about not being able to connect. Could you try with --remote-tab-wait and see if anything is printed to :messages?

I have tested it.  No error messages.

2022-03-31 02:08 UTC, Shougo commented
> $EDITOR should be nvim --server ~/.cache/nvim/server.pipe --remote-tab-wait-silent to connect to the Neovim listening on that pipe.

Yes.  I have set and it works.  Because the editor is executed in the neovim terminal.  Oh no.

I have tested it by deol.nvim.

https://github.com/Shougo/deol.nvim/blob/master/autoload/deol.vim#L238

2022-03-31 02:16 UTC, Shougo commented
Hm....  It seems the server feature does not work.

```
nvim --listen ~/.cache/nvim/server.pipe --clean
```

And

```
nvim --server ~/.cache/nvim/server.pipe --remote-tab-wait-silent ~/work/test2.ts --clean
```

It does not work.  Because `test2.ts` is opened new neovim tab.
Please tell me the correct instruction.

2022-03-31 21:53 UTC, justinmk commented
I don't quite understand why we need all of the random variants of Vim's `--remote-foo` CLI args. We only really need one: `--remote`. Anything else should be easy to do via Lua or Vimscript. If it's not, then that should be fixed rather than having a bunch of clunky special-purpose CLI options.

2022-04-01 14:08 UTC, groves commented
> I don't quite understand why we need all of the random variants of Vim's --remote-foo CLI args.

I'd also lose the tab and silent variants if I were designing this from scratch. I see keeping the variants as allowing ease of migration from Vim and to allow people to write scripts and instructions that work for both. This feels like part of the API that we keep in the same way that we keep a bunch of clunky bits of Vimscript and builtin functions.

2022-04-02 06:18 UTC, Shougo commented
OK.  I get it.  It seems works.
But it has strange behavior.

If I open the file by `~/src/neovim/build/bin/nvim --clean --server ~/.cache/nvim/server.pipe --remote-tab-wait ~/work/test2.ts`, the file is opened both remote neovim and local neovim.  Why?

2022-04-02 06:23 UTC, Shougo commented
> This does make me wonder if we should have a user visible message if we fail to start the server on an address given in --listen

I think `--listen` error message should be printed like `--server` error.

2022-04-18 20:43 UTC, groves commented
> If I open the file by `~/src/neovim/build/bin/nvim --clean --server ~/.cache/nvim/server.pipe --remote-tab-wait ~/work/test2.ts`, the file is opened both remote neovim and local neovim. Why?

This is a bug I introduced on this branch. Should be fixed now. Thanks for finding it!

Feel free to give that fix a try, but I should warn you that there are likely to be other issues. I still have a few things I need to address before bumping this PR from draft to ready.

2022-04-19 00:35 UTC, Shougo commented
Oh, thank you for the fix.  I will try again later.

2022-04-19 00:42 UTC, Shougo commented
The feature is broken now...

```
$ ~/src/neovim/build/bin/nvim --clean --server ~/.cache/nvim/server.pipe --remote-tab-wait ~/work/test2.ts
Error executing lua: Vim:Error invoking 'nvim_exec_lua' on channel 3:
Error executing lua: [string "<nvim>"]:1: attempt to call field '_remote_server_edit' (a nil value)
stack traceback:
	[string "<nvim>"]:1: in main chunk
stack traceback:
	[C]: in function 'rpcrequest'
	vim/_editor.lua:742: in function <vim/_editor.lua:692>
```

2022-04-23 20:42 UTC, justinmk commented
>  I see keeping the variants as allowing ease of migration from Vim and to allow people to write scripts and instructions that work for both. This feels like part of the API that we keep in the same way that we keep a bunch of clunky bits of Vimscript and builtin functions.

Such a migration won't work except for trivial cases.  

So I'm not seeing a strong reason to add anything more than `--remote` and `--remote-wait`. I'd even try to remote `--remote-wait`. If someone wants "async" behavior that can be done with `timer_start`, `vim.defer_fn`, etc.

2022-04-23 20:48 UTC, justinmk requested changes
Before continuing with this, I'd like to see a table comparing the equivalent `--remote foo` command to the `--remote-foo` variant. For example:


|old|new|
|--------------------|-----------------------------------|
|--remote-send "foo" | --remote "call feedkeys('foo')" |
|--remote-blah | --remote "blah" |

We should not add things just because Vim did it. There needs to be a good reason.

- The Lua/Vimscript API has many more features today than it did when Vim added these things. 
- Providing examples of using Lua/Vimscript _helps_ users understand and connect concepts.
    - Likewise, providing shallow "sugar" that does very little, _actually harms users_ by increasing the burden of useless "knowledge" and decreasing the weight of composable concepts (the API).

2022-04-26 14:34 UTC, groves commented
>> I see keeping the variants as allowing ease of migration from Vim

> Such a migration won't work except for trivial cases. 
> Providing examples of using Lua/Vimscript helps users understand and connect concepts. Likewise, providing shallow "sugar" that does very little, actually harms users by increasing the burden of useless "knowledge" and decreasing the weight of composable concepts (the API).

This makes a perfect sense to me if Neovim were a new editor. In that scenario, the best thing for users is to have a clear path from starting out to mastery of a simple, powerful set of customization tools.

In my understanding, Neovim's scenario has more nuance. At least as I've internalized Neovim's values, one of those is an easy transition for Vim users. That doesn't invalidate your point about helping users towards the best Neovim tools, but it adds a possibly conflicting desire to make existing Vim idioms and APIs work well.

Like with any big project, there are even more competing desires for Neovim's direction. To complete the picture as I understand it, this is what I roughly see as the Neovim desires in order of importance:

- **Ease of maintenance** - does the addition make it easier to make future additions or at least not make future additions harder
- **Power and ease as an editor platform** - does the addition allow users to do something new or do things with less fiddling
- **Drop-in Vim** - does the addition let existing Vim users use Neovim without having to first learn Neovim before getting started

I'm not laying these out here to try and convince you that those are the right desires. I'm really trying to elicit what the desires are as envisaged by the Neovim maintainers. My having a better sense of the desires will help me make proposals that better track with those desires. If that's already on the web somewhere that I haven't seen, a link to that is plenty good.

What you're suggesting about comparing the Vim approach with a minimal Neovim approach makes sense to me as a way to decide if and how to proceed with this. I'd like to add in how well each of those items fit with the overall desires to make it a complete picture.

2022-04-26 14:45 UTC, clason commented
Not speaking for the rest of the team here, but I don't think

> Drop-in Vim - does the addition let existing Vim users use Neovim without having to first learn Neovim before getting started

is really a strong project goal (anymore). What we _do_ care about is backwards compatibility for the plugin ecosystem, so Neovim users can still use Vim plugins (even though they themselves are not expected to use legacy syntax, if better alternatives exist). So (only) if not supporting a particular Vim option would _break_ a useful plugin, that would count as a valid argument in favor of including it.

2022-04-27 18:19 UTC, justinmk commented
> There is a big use case for `--remote-wait` in my view:

Re-read my previous comments. I've no objection to `--remote-wait` functionality, in fact I am suggesting that `--remote` acts like `--remote-wait`. And the "non-blocking" nature of `--remote` can be achieved with things like `timer_start()` (we can make this more ergonomic by adding a command like `:async` or `:job`).

So to be clear, I'm suggesting that `--remote` is the only thing we need. We don't need the 17 other variants, they are shallow sugar.

2022-04-27 18:30 UTC, jcorbin commented
> > There is a big use case for `--remote-wait` in my view:
> 
> So to be clear, I'm suggesting that `--remote` is the only thing we need. We don't need the 17 other variants, they are shallow sugar.

Oh, I see! Thank you so much for clarifying, was confused after 0.7 shipped a non-blocking `--remote`, and hadn't quite read every comment fully, so I wasn't quite sure as an (albeit early adopter) user where this was all going, and wanted to provide some use case feedback :-)

2022-04-28 18:43 UTC, groves commented
> > At least as I've internalized Neovim's values, one of those is an easy transition for Vim users.

> That doesn't apply to --remote, it's a very niche, one-off use-case. Typically used for setting up desktop shortcuts or small scripts. And those aren't going to be "drop in", no matter how much we aesthetically, superficially match the spelling of the old Vim --remote-x variants.

That was exactly my usage of `--remote` in Vim, I had a shell script that would let me edit a file in a running Vim from terminals I'd opened later that had nothing to do with that Vim. I bounced off of Neovim a couple years ago because there wasn't an obvious way to do that. Having `--remote` and something akin to `--servername` would have been a drop-in for my use case.

I don't understand the use of the tab and silent variants, and the send and expr variants are silly in the light of Neovim's API. I have no concern with dropping those, though as @jcorbin pointed out, the non wait versions of all of them shipped in 0.7. They add almost no code compared to the bulk of stuff needed for `--remote-wait`.

As it stands, there's a functional version of the wait variations on this branch now. I was planning on adding a couple more tests and finishing up the docs before marking it ready for review. 

I'm happy to finish it up if someone wants to write up a design for where this should end up. I'm also perfectly happy if someone else wants to take it from here.

2022-04-29 05:21 UTC, Shougo commented
> Before continuing with this, I'd like to see a table comparing the equivalent --remote foo command to the --remote-foo variant. For example:

If the same features are works, I don't need subcommands yeah.

But I want to use neovim remote feature as `$EDITOR`.

In `$EDITOR`, the feature must be `{command} {filename}`.  Because `{filename}` is added by external command like `git`.

It works as expected in `neovim-remote`:
`$EDITOR = 'nvr --remote-tab-wait-silent`

It does not work in neovim remote features.

`$EDITOR = 'nvim --clean --server ~/.cache/nvim/server.pipe --remote-send "tabnew | {filename}"'`
`filename` cannot be added.

So I need the feature.

2022-04-30 05:59 UTC, justinmk commented
> They add almost no code compared to the bulk of stuff needed for --remote-wait.

The main cost is the user interface (which includes documentation, and noise in `--help`).

Waiting to see the table requested in https://github.com/neovim/neovim/pull/17856#pullrequestreview-951127037

2022-05-02 06:25 UTC, Shougo commented
> Waiting to see the table requested in https://github.com/neovim/neovim/pull/17856#pullrequestreview-951127037

Please see below table.

| Legacy (Vim) | Minimal (Nvim, with always-non-blocking --remote)
| --- | --- |
| --remote "foo" | --remote "foo"
| --remote +cmd "foo" | Not implemented yet
| --remote-silent "foo" | --remote-silent "foo"
| --remote-silent +cmd "foo" | Not implemented yet
| --remote-wait "foo" (blocking) | Not implemented yet
| --remote-wait-silent "foo" (blocking) | Not implemented yet
| --remote-tab "foo" | --remote-tab "foo"
| --remote-tab-silent "foo" | --remote-tab-silent "foo"
| --remote-tab-wait (blocking) | Not implemented yet
| --remote-tab-wait-silent (blocking) | Not implemented yet
| --remote-send "foo" | --remote-send "foo"

I think wait variants and `+cmd` support is only needed for neovim.
Other features are almost implemented.
So the PR is important.

2022-05-04 14:25 UTC, justinmk commented
@Shougo thanks. But that table doesn't give examples of what the interface would look like _without_ the numerous `--remote-x-y` variants. I'm asking for this so that we have a concrete idea of why (or if) the variants are needed.

I've sketched out a proposed interface in https://github.com/neovim/neovim/pull/18414

2025-12-16 05:30 UTC, justinmk commented
Path forward is tracked in https://github.com/neovim/neovim/pull/18414 (still needs discussion)

2025-12-16 05:30 UTC, closed without merging