fix: always close libuv references on exit
neovim/neovim pull request #18582
Opened 2022-05-15 19:46 UTC by gpanders

Ref: https://github.com/neovim/neovim/pull/11887

2022-05-15 20:44 UTC, justinmk approved these changes
lgtm if CI passes, but need a brief explanation of the reasoning in the commit message -- this stuff is hard to remember years later :)

2022-05-16 09:39 UTC, bfredl commented
I'd like some way to _opt-in_ to this check. It catches _real_ resource leaks when working on event code on the c side, most recently with #18375 . An option is to enable it specifically for ASAN/UBSAN builds (which also catches memory leaks), which was the status quo before #17783 .

2022-05-16 10:16 UTC, justinmk requested changes
> Now that EXITFREE is defined in Debug builds by default, this causes a 2 second delay upon each exit which quickly becomes annoying.

I didn't realize this was motivated by https://github.com/neovim/neovim/pull/17783 . I thought this was motivated by a CI issue.

Who is using DEBUG builds except for testing (where this is actually needed)? I'd say we either need to revert #17783 or DEBUG builds should just live with this annoyance.

2022-05-16 10:25 UTC, dundargoc commented
> I'd say we either need to revert https://github.com/neovim/neovim/pull/17783 or DEBUG builds should just live with this annoyance.

I'd vote for reverting in that case - don't want annoy my neovim peers with slow debug builds :)

2022-05-16 12:50 UTC, gpanders commented
> > I'd say we either need to revert #17783 or DEBUG builds should just live with this annoyance.
> 
> I'd vote for reverting in that case - don't want annoy my neovim peers with slow debug builds :)

Sure, let’s go with that then.

2022-05-16 12:50 UTC, closed without merging

2022-05-17 00:45 UTC, justinmk commented
> > > I'd say we either need to revert #17783 or DEBUG builds should just live with this annoyance.
> > 
> > 
> > I'd vote for reverting in that case - don't want annoy my neovim peers with slow debug builds :)
> 
> Sure, let’s go with that then.

Let's leave it as-is for awhile. Until now, the un-disposed resources were "hidden". Maybe this will lead to a fix.