feat(uri): accept 'scheme:path' as valid url
neovim/neovim pull request #19967
Opened 2022-08-27 08:33 UTC by sigmaSd

Unfortunately #19797 is not enough to handle all cases.

Some lsps like (deno) actually do use `scheme:path`

This PR is an attempt to accept `scheme:path` in nvim as valid url which would make it spec compliant.

One note: is `URL_BACKSLASH` still needed or is it possible to remove it? (it doesn't exist in the spec)

2022-08-27 09:15 UTC, zeertzjq commented on src/nvim/testdir/test_gf.vim
> +  call assert_equal('Xfile:4', bufname('%'))
Why modify this test?

2022-08-27 09:19 UTC, zeertzjq requested changes, later dismissed

2022-08-27 09:19 UTC, zeertzjq commented on src/nvim/testdir/test_gf.vim
> +  call assert_equal('Xfile:4', bufname('%'))
Can you make this test pass without being modified?

2022-08-27 09:19 UTC, sigmaSd commented
I'm currently just modifying tests to see how far can it goes and what else will break

2022-08-27 10:41 UTC, sigmaSd commented
Ok the good news is only two tests needs to be disabled

https://github.com/neovim/neovim/pull/19967/files#diff-59d0bc03d4c61e04a234f80256da1c69f33547371df84fc251493fdce2c1e498R62
https://github.com/neovim/neovim/pull/19967/files#diff-59d0bc03d4c61e04a234f80256da1c69f33547371df84fc251493fdce2c1e498R65

These now expect Xfile:number beacuse this:isafile is now a valid url and thus it shows up in bufname

2022-09-30 18:06 UTC, sigmaSd commented
@zeertzjq deno is probably going to accept this pr <https://github.com/denoland/deno/pull/16023> which will fix deno on nvim by not using `scheme:path`

So now I don't have practical use case for this anymore.

Should I keep this open or just close it?

2022-10-01 17:18 UTC, justinmk commented
> deno is probably going to accept this pr [denoland/deno#16023](https://github.com/denoland/deno/pull/16023) which will fix deno on nvim by not using `scheme:path`
> 
> So now I don't have practical use case for this anymore.
> 
> Should I keep this open or just close it?

Using a colon without slash(es) is a pretty obscure and pedantic way to represent a URI. 

However, we could try this on master for a bit and see what happens. If there are no objections please remind me in a week or so.

2022-10-01 17:20 UTC, justinmk commented on src/nvim/testdir/test_gf.vim
> + "call assert_equal(4, getcurpos()[1])
This is a somewhat important feature of vim. Perhaps `path_is_url` can check if the part immediately after the colon is a number? If deno is using `deno:<number>`, well...

2022-10-01 19:34 UTC, sigmaSd commented
https://github.com/denoland/deno/pull/16023 was merged and I tested and it works correctly with nvim.

I think I'll just close this it seems too much of a trouble now with no clear benefit.

thanks for your feedback

2022-10-01 19:34 UTC, closed without merging