feat(lua): add vim.bufcall and vim.wincall
neovim/neovim pull request #20669
Opened 2022-10-15 11:31 UTC by lewis6991

Ergonomic wrappers for nvim_buf_call and nvim_win_call

2022-10-15 12:11 UTC, vhyrro commented
Perhaps the names `winwrap` and `bufwrap` would be more suitable here? :eyes:

2022-10-15 12:23 UTC, lewis6991 commented
I don't think so as "wrap" functions return other functions whereas these do not.

2022-10-15 12:27 UTC, vhyrro commented
Oh right, that's true. Just feels like using `call` for both versions of the functions can become a little confusing, since `vim.api.nvim_win_call` is actually calling a function whereas `wincall` is, wrapping a function then calling it 🤔

2022-10-15 12:29 UTC, lewis6991 commented
The fact it is wrapping and call is an implementation detail and shouldn't influence the interface.

If we wanted we could implement this directly in C.

2022-10-16 00:56 UTC, justinmk commented
Sugar like this can be very nice if it's pervasive, but I'm not in favor of lots of shallow wrappers around API things. And this is very shallow indeed, it's almost totally cosmetic. We should think about higher-level interfaces and patterns.

> I don't think so as "wrap" functions return other functions whereas these do not.

"wrap" is also not something we should perpetuate. The "wrap" functions were a compromise, not guideline.

2022-10-16 01:03 UTC, justinmk requested changes
in favor of a higher-level concept, not in favor of new API surface area for minor cosmetic sugar

2022-10-17 08:55 UTC, lewis6991 commented
@justinmk: thanks for your thoughts on this, I appreciate them and mostly agree.

I put this PR out without any context just to see what the opinions would be. However here's a more detailed rationale for this.

The main motivation for this is just to be able to pass in function arguments to `api.nvim_buf/win_call`, however we can't do that because:
- API contract
- API doesn't support varargs (though an array could be used).

But mainly, `nvim_buf/win_call` are Lua only, so it doesn't make sense to have them in the API. For more context this was discussed in #19164 and matrix, and the agreement was that Lua only stuff should be kept away from the API. This is what motivated #19239.

Furthermore, here's the current list of Lua only functions in the API:
- `nvim_buf_call`
- `nvim_win_call`
- `nvim_set_decoration_provider`.

### Proposal

- deprecate `nvim_buf/win_call` (to be removed in 2.0)
- add `vim.bufcall` `vim.wincall` to replace said deprecated functions
- maybe consider some API-contract for Lua API (TBD when to be enforced).
- at some point, re-implement `vim.bufcall` and `vim.wincall` directly in C (possibly using #19239).

### Notes

- I think the suggestion of `vim.with` is a good one, however I would predicate that on it being able to specify more than just `buf` and `win`. Since these functions are basically just `bufdo` and `windo`, It might make sense to use the mods used for ex commands: `silent`, `noautocmd`, `verbose`, `keep*`.
  ```lua
  vim.with({buf=2}, fn, arg1, arg2) -- Run fn for buffer 2
  vim.with({buf=true}, fn, arg1, arg2) -- Run fn for all buffers
  vim.with({win=1001, silent=true}, fn, arg1, arg2) -- Run fn for window 1001 and silence any output.
  ```
- This overlaps with #20632, so we should think out a full design first.

2022-10-17 11:22 UTC, ii14 commented
Related issue: #19832

2022-10-18 11:48 UTC, justinmk commented
> The main motivation for this is just to be able to pass in function arguments to `api.nvim_buf/win_call`, however we can't do that because:
> 
> * API contract
> * API doesn't support varargs (though an array could be used).
> 
> But mainly, `nvim_buf/win_call` are Lua only, so it doesn't make sense to have them in the API.

We can relax the API contract (and document this) for Lua-only APIs. Mainly we care about not breaking RPC clients.

> Lua only stuff should be kept away from the API. 

If they're marked `FUNC_API_LUA_ONLY` , is there any problem?

> deprecate nvim_buf/win_call (to be removed in 2.0)
> add vim.bufcall vim.wincall to replace said deprecated functions
> maybe consider some API-contract for Lua API (TBD when to be enforced).

I see `FUNC_API_LUA_ONLY` as giving us all the automation and formalism of the API subsystem, with a separate contract (TODO: `:help api-contract-lua`) + potential for graduating them to RPC or C (`libnvim`) later.

BTW, would a "thunk generator" address the immediate need here?

```
-- Creates a thunk that applies the args `...` to `fn`.
function vim.f(fn, ...)
  return function()
    return fn(...)
  end
end
```

2022-10-19 09:16 UTC, lewis6991 commented
> We can relax the API contract (and document this) for Lua-only APIs. Mainly we care about not breaking RPC clients (and libnvim in the future).

I assume you mean to allow signatures of Lua-only API's to change, providing they are *reasonably* backwards compatible? e.g: adding new arguments, dropping arguments, making argument types polymorphic? If so then we probably need to re-consider #15302 since at the moment arguments checks are strict in the Lua-API.

> If they're marked FUNC_API_LUA_ONLY , is there any problem?

The main problem, which is significant to me, is guidance on whether something should be added to `vim.*` or `vim.api.*`. In #19164 I argued that `vim.ui_attach` should be added to the API, but after discussion we agreed adding to `vim.*`, and the policy of adding Lua-only to `vim.*` makes the decision on where to add things much more clear cut.

>  see FUNC_API_LUA_ONLY as giving us all the automation and formalism of the API subsystem, with a separate contract (TODO: :help api-contract-lua) + potential for graduating them to RPC or C (libnvim) later.

Usually if something could be graduated to RPC, we can do it from the start. I'm not sure if there is any scope whatsoever to allow funcrefs in RPC as it is a fundamental limitation? The case is different for libnvim but that doesn't exist yet.

> BTW, would a "thunk generator" address the immediate need here?

Yes it would actually!  It would also allow `vim.schedule` to be more ergonomic. Though I would still argue adding var-args to the end of `vim.schedule` would be worth doing.

It would make sense to put this in `F.lua` so we could have `vim.F.f` or `vim.F.wrap`.

2022-10-19 11:43 UTC, justinmk commented
> It would make sense to put this in `F.lua` so we could have `vim.F.f` or `vim.F.wrap`.

Don't want vim.F to be a public interface (and we need to deprecate it, it doesn't meet naming conventions). Functional utils should live directly on `vim.*` (or maybe `vim.f.*` / `vim.fun.*`).

> I assume you mean to allow signatures of Lua-only API's to change, providing they are _reasonably_ backwards compatible? e.g: adding new arguments, dropping arguments, making argument types polymorphic? If so then we probably need to re-consider #15302 since at the moment arguments checks are strict in the Lua-API.

Yeah we would need to relax the API checks for FUNC_API_LUA_ONLY. I can't find a "guidance" issue about when to choose `nvim/lua/` vs `FUNC_API_LUA_ONLY`. Question is, if `nvim_set_decoration_provider` / `nvim_buf_call` instead lived in `vim.*`, what would we gain/lose in terms of development cost? Do we actually need `FUNC_API_LUA_ONLY` or should we always add to `vim.*` directly? @bfredl

2022-10-19 11:59 UTC, bfredl commented
@justinmk Some convenience in terms of development cost (converting params and return values, also, documentation Just Works), but we could of course disentangle the generator so it can be used outside of the `vim.api.*` namespace. I think lewis did a sketch in that direction a while ago :) https://github.com/neovim/neovim/pull/19239/files

2022-10-19 12:57 UTC, justinmk commented
Sounds like #19239 is the path forward, then we can eliminate FUNC_API_LUA_ONLY.

2024-05-05 14:46 UTC, closed without merging