feat: add args.client for LspAttach callback
neovim/neovim pull request #20717
Opened 2022-10-18 12:42 UTC by adoyle-h

Many LSP modules ([aerial](https://github.com/stevearc/aerial.nvim), [navic](https://github.com/SmiteshP/nvim-navic), [lsp-format](https://github.com/lukas-reineke/lsp-format.nvim)) need client as `on_attach` function argument.
It is convenient that returns `args.client` for users.

```lua
callback = function(args)
  -- local client = vim.lsp.get_client_by_id(args.data.client_id)
  local client = args.client
  require('aerial').on_attach(client, args.buf)
end,
```

2022-10-18 13:18 UTC, gpanders commented
Client ID is already passed in the data field (which is where arbitrary data should go, not at the top level). We discussed passing the client directly but decided to stick with the client ID because the client object is not always serializable (important for RPC clients).

2022-10-20 10:44 UTC, adoyle-h commented
@gpanders 

Return client directly doesn't affect RPC clients. The `data.client_id` is not removed in the PR.

```
client = client,
data = { client_id = client.id },
```

`client` field could be skipped for RPC and used for native. RPC clients can get clientId from `data.client_id`. Native user can get client from `client` field.

2022-10-20 10:54 UTC, glepnir commented
Maybe some examples at the beginning use the `on_attach` field? . So these plugins use the `on_attach` field? It's not the only way. They can totally do without `on_attach`.

2022-10-20 11:07 UTC, adoyle-h commented
@glepnir

These plugins need client and buffer number that `on_attach` function arguments passed. For example, see [aerial](https://github.com/stevearc/aerial.nvim/blob/d35799b510f6582f24765dcb8b293fc4988ccc41/lua/aerial/backends/lsp/init.lua#L98-L111).

And the usage of `on_attach` follows its definition. We don't need another way.

https://github.com/neovim/neovim/blob/e6f7e038b8bbca487e78ebfc6fe21d6852330623/runtime/doc/lsp.txt#L641-L642

2022-10-20 11:26 UTC, glepnir commented
there has  api can get client object  by id . is it not enough ?

2022-10-20 11:46 UTC, adoyle-h commented
> there has api can get client object by id . is it not enough ?

Every plugin use LspAttach autocmd should call `vim.lsp.get_client_by_id(args.data.client_id)` to get client. It is redundant.

It is convenient that `nvim_exec_autocmds` pass the `client`.

2022-10-20 12:51 UTC, clason commented
_Your_ convenience, at the cost of _our_ inconvenience. Two lines instead of one does not justify the additional implementation, documentation, maintenance, and testing effort.

2022-10-20 13:13 UTC, adoyle-h commented
@clason  I will try to cover all these costs. Current PR has bug. I will write test cases and submit another PR.

I think the problem is not the costs, but whether LspAttach return client directly is acceptable or not in design.

2022-10-20 13:19 UTC, clason commented
> I think the problem is not the costs, but whether LspAttach return client directly is acceptable or not in design.

And whether it is depends exactly on the cost...

But the cost may have changed since `LspAttach` was implemented (due to changes to core), so it's indeed reasonable to revisit this decision now.

But the point that this needs to be a member of `data`, not its own top-level field, remains.

2022-10-20 13:31 UTC, adoyle-h commented
> But the cost may have changed since LspAttach was implemented (due to changes to core), so it's indeed reasonable to revisit this decision now.

So where to talk about the decision? Is there any relevant issue?

> But the point that this needs to be a member of `data`, not its own top-level field, remains.

Yes, thanks for reminding me. I'm reading the codes.

2022-10-20 14:32 UTC, gpanders commented
I had to go back and revisit some of the discussion around this. There was an issue with serializability for the `client` object, but that should not be a real problem in practice since Lua autocommand callbacks are only usable from Lua, not from RPC clients.

So it looks like a (small) mistake on our part. Passing the `client` object directly is the better design choice, I think. Thanks @adoyle-h for bringing this up so we could re-visit it.

Please:

1. Move the `client` object into the `data` table (not at the top level)
2. Add/update the tests in `lsp_spec` to test for the client object being passed to the callback

2022-10-20 14:38 UTC, gpanders requested changes
Please also update the test in `lsp_spec.lua` to test for the `client` object being passed directly.

2022-10-20 14:38 UTC, gpanders commented on runtime/lua/vim/lsp.lua
> +      client = client,
This should be in the `data` table

2022-10-20 14:39 UTC, gpanders commented on runtime/doc/lsp.txt
> +        local client = args.client
```suggestion
        local client = args.data.client
```

2022-10-20 14:39 UTC, gpanders commented on runtime/doc/lsp.txt
> +        local client = args.client
```suggestion
        local client = args.data.client
```

2022-12-17 01:56 UTC, closed without merging