build: move oldtests to test directory
neovim/neovim pull request #22536
Opened 2023-03-05 12:51 UTC by dundargoc

Tests should be under the test directory.

2023-03-05 12:51 UTC, dundargoc commented
See also: https://github.com/neovim/neovim/issues/21559#issuecomment-1368248698

2023-03-05 13:41 UTC, zeertzjq requested changes, later dismissed
Did you read the next comments?

> Would moving it to test/old/testdir avoid most of the pain?

2023-03-05 13:42 UTC, zeertzjq commented
Oops, can't dismiss review.

2023-03-05 13:47 UTC, zeertzjq commented on .gitattributes
This file doesn't exist
```suggestion
```

2023-03-05 14:57 UTC, zeertzjq commented
https://github.com/vim/vim/pull/12111

2023-03-06 23:31 UTC, zeertzjq approved these changes

2023-03-07 01:57 UTC, justinmk approved these changes
Nice!

2023-03-07 03:13 UTC, merged