feat(treesitter): add support for setting query depths
neovim/neovim pull request #22710
Opened 2023-03-17 15:03 UTC by lewis6991

2023-04-04 12:04 UTC, clason commented
I think we'll need to guard this behind a feature flag since this won't be in a release anytime soon. 

(See https://github.com/neovim/neovim/pull/14930)

2023-04-04 12:11 UTC, lewis6991 commented
I initially only raised this so I could test ts-context. I'm happy for this to live here for a while.

I'm not sure a feature flag is the best idea since it heavily changes the semantics.

2023-04-17 09:06 UTC, clason commented
upstream PR is merged now; now we just have to wait for a new release.

2023-05-10 09:53 UTC, clason commented
Maybe add a todo note in both locations to remove this when the minimum required version of treesitter is bumped to 0.20.9.

(Or we can wait for that release and just bump with this PR?)

2023-05-11 08:21 UTC, lewis6991 commented
Good to go?

2023-05-11 08:46 UTC, dundargoc requested changes

2023-05-11 08:46 UTC, dundargoc commented on cmake/FindTreesitter.cmake
> +list(APPEND CMAKE_REQUIRED_LIBRARIES "${TREESITTER_LIBRARY}")
You need to remove these entries after the check

2023-05-11 10:11 UTC, clason approved these changes

2023-05-11 10:13 UTC, merged