fix(float): position fix when relative is win
neovim/neovim pull request #25126
Opened 2023-09-13 02:37 UTC by glepnir

2023-09-13 09:52 UTC, justinmk commented on src/nvim/window.c
> +    for (win_T *wp = ((tp) == curtab) ? lastwin : (tp)->tp_lastwin; wp != NULL; wp = wp->w_prev){
```suggestion
    // Iterate in _reverse_ order.
    for (win_T *wp = ((tp) == curtab) ? lastwin : (tp)->tp_lastwin; wp != NULL; wp = wp->w_prev){
```

2023-09-13 09:56 UTC, justinmk commented on test/functional/ui/float_spec.lua
> +  it('win render order issue #14735', function()
```suggestion
  it('relative=win is relative to given (floating) window #14735', function()
```

2023-09-13 09:59 UTC, justinmk approved these changes
LGTM after comments, assuming CI passes.

2023-09-13 10:04 UTC, zeertzjq requested changes

2023-09-13 10:04 UTC, zeertzjq commented on src/nvim/window.c
> +    int row = (int)c.row, col = (int)c.col;
Revert

2023-09-13 10:18 UTC, justinmk commented
uncrustify is flagging something in src/nvim/window.c

2023-09-13 10:22 UTC, zeertzjq requested changes
I don't think this is the correct solution. If an older floating window is reconfigured to be relative to a newer floating window then this won't work.

2023-09-13 10:28 UTC, glepnir commented
change relative to new window ? hmm let me try reproduce it ...

2023-09-13 10:38 UTC, zeertzjq commented
This works fine without this PR, but is broken with this PR
```lua
local function test_nvim()
  local parent_bufnr = vim.api.nvim_create_buf(false, true)
  local bufnr = vim.api.nvim_create_buf(false, true)

  local initial_opts = {
    width = 5,
    height = 5,
    row = 5,
    col = 5,
    relative = "editor",
    style = "minimal",
  }
  local win_id = vim.api.nvim_open_win(bufnr, false, initial_opts)
  local parent_winid = vim.api.nvim_open_win(parent_bufnr, false, initial_opts)

  local parent_window_config = {
    width = 10,
    height = 6,
    row = 10,
    col = 20,
    relative = "editor",
    style = "minimal",
    border = "rounded",
    zindex = 49,
  }

  vim.api.nvim_win_set_config(parent_winid, parent_window_config)

  vim.api.nvim_win_set_option(parent_winid, "winhighlight", "Normal:Normal")

  local opts = {
    width = 8,
    height = 4,
    row = 1,
    col = 1,
    relative = "win",
    style = "minimal",
    win = parent_winid,
    zindex = 50,
  }

  vim.api.nvim_win_set_config(win_id, opts)

  return vim.api.nvim_win_get_position(win_id)
end

test_nvim()
```

2023-09-13 10:41 UTC, glepnir commented
thanks.

2023-09-13 14:38 UTC, closed without merging

2023-09-14 00:29 UTC, glepnir commented
hmm seems to be doing the same thing. Add grid recursively