fix(snippet): expand TM_FILENAME_BASE to filename without any extensions
neovim/neovim pull request #26119
Opened 2023-11-20 14:23 UTC by Kibadda

Problem:
vim.snippet variable `TM_FILENAME_BASE` only removes last extension of filename.

Steps:
1. nvim --clean test.many.extensions.lua
2. `i`
3. `<C-o>`
4. `:lua vim.snippet.expand("${TM_FILENAME_BASE}")<CR>`

Result:
test.many.extensions

Solution:
Change replacement in snippet.lua
As the [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax) says, `TM_FILENAME_BASE` should expand to the filename without any extensions.

2023-11-20 16:20 UTC, MariaSolOs commented
@Kibadda as you can see from the comments in the code, we know that the variable should exclude all extensions. However I don’t see how your change fixes the issue. The current regex ensures that the extension stops at a `.`, while your change removes that check.

Could you please add a couple of tests to verify your change (and also show that the current implementation is wrong)?

2023-11-20 16:21 UTC, MariaSolOs requested changes
@Kibadda as you can see from the comments in the code, we know that the variable should exclude all extensions. However I don’t see how your change fixes the issue. The current regex ensures that the extension stops at a `.`, while your change removes that check.

Could you please add a couple of tests to verify your change (and also show that the current implementation is wrong)?

2023-11-21 07:06 UTC, Kibadda commented
Maybe I didn't understand the specification correctly.
I thought that in a file called `Test.class.php` `TM_FILENAME_BASE` should insert `Test`.
If that is wrong I will close this PR. :)

2023-11-21 07:26 UTC, MariaSolOs commented
@Kibadda You're correct. I tested your change locally and I can see why the regex works now. It would be great if you can add a small test though :)

2023-11-21 07:27 UTC, Kibadda commented
Ok I'll add some tests :)
Do we know what should happen with filenames that start with a dot?
Should `TM_FILENAME_BASE` insert an empty string then?

2023-11-21 07:30 UTC, MariaSolOs commented
> Ok I'll add some tests :) Do we know what should happen with filenames that start with a dot? Should `TM_FILENAME_BASE` insert an empty string then?

Yeah it would be an empty string, but don't worry about those edge cases. With such a filename there is probably a more serious bug than weird snippet expansions.

2023-11-21 07:50 UTC, closed without merging

2023-11-21 08:10 UTC, MariaSolOs commented
As discussed on Matrix, we decided to close this PR since other editors following the LSP and snippet libraries just remove the last extension, and even the Wikipedia page suggests that only the last extension is relevant: “File systems for UNIX-like operating systems also store the file name as a single string, with "." as just another character in the file name. A file with more than one suffix is sometimes said to have more than one extension, although terminology varies in this regard, and most authors define extension in a way that does not allow more than one in the same file name”