feat[rpc] add nvim_get_api_info
neovim/neovim pull request #27321
Opened 2024-02-03 13:05 UTC by nikolightsaber

#21291

Hi first time doing this. I tried to follow the guidelines. I hope documentation and testing is good enough.

For testing I tried to follow `nvim_get_api_info()` but i did not find unit tests on this. I figured changing some of the `nvim_get_api_info()[1]` should be good enough for such a simple change.

Thanks for the feedback.

2024-02-07 19:42 UTC, justinmk requested changes
Let's try to avoid adding a new api function. Why can't we do this: https://github.com/neovim/neovim/issues/21291#issuecomment-1455212995

> Instead, we could make `nvim_get_chan_info(0)` (that is, "zero" means "current channel") work.

If that doesn't work, I'm starting to think we should relax `:help api-contract` to allow `void` return values to be changed.

2024-02-07 22:46 UTC, nikolightsaber commented
@justinmk I think i succeeded in `nvim_get_chan_info` handling 0 as an argument.

I figured that channel 0 is impossible as nvim always seem to start at 3.

I'm a bit confused on the doc and linting pipeline failing. Could it be an issue unrelated to my changes ?

The test that fail seem to be my changes as the have to to with channels. I will have a look at them if needed.

I would appreciate a review at this stage.

Thanks

2024-02-07 22:50 UTC, zeertzjq commented on runtime/doc/news.txt
> +  channel
```suggestion
• Passing 0 to |nvim_get_chan_info| gets channel info for the current channel.
```

2024-02-07 22:51 UTC, zeertzjq commented on src/nvim/api/vim.c
> +    chan = (Integer) channel_id;
```suggestion
    chan = (Integer)channel_id;
```

2024-02-07 22:52 UTC, zeertzjq commented on src/nvim/api/vim.c
> +    assert(channel_id <= INT64_MAX);
Internal calls will fail this assertion:
```c
/// Mask for all internal calls
#define INTERNAL_CALL_MASK (((uint64_t)1) << (sizeof(uint64_t) * 8 - 1))

/// Internal call from Vimscript code
#define VIML_INTERNAL_CALL INTERNAL_CALL_MASK

/// Internal call from Lua code
#define LUA_INTERNAL_CALL (VIML_INTERNAL_CALL + 1)
```

2024-02-07 22:55 UTC, zeertzjq commented on src/nvim/api/vim.c
> +  if (chan == 0) {
```suggestion
  if (chan == 0 && !is_internal_call(channid_id)) {
```

2024-02-07 23:05 UTC, nikolightsaber commented
Thanks for the review @zeertzjq I implemented the changes.

2024-02-07 23:18 UTC, zeertzjq commented on test/functional/api/vim_spec.lua
> +      eq(testinfo, api.nvim_get_chan_info(0))
I think this should be moved to the `stream=stdio channel` block, before both `eq(testinfo, api.nvim_get_chan_info(1))` assertions.

2024-02-08 00:47 UTC, justinmk approved these changes
please explain what problem this is solving, in the commit message

2024-02-08 10:49 UTC, zeertzjq approved these changes

2024-02-08 10:59 UTC, merged

2024-02-08 11:02 UTC, nikolightsaber commented
Hi @justinmk, @zeertzjq thanks for the help with this.  I enjoyed learning about the api. Quite clever with the generated code. 

I hope I can contribute some more if I find some time.