feat(treesitter): inject into bash file redirects
neovim/neovim pull request #27832
Opened 2024-03-12 13:28 UTC by lewis6991

2024-03-12 13:32 UTC, clason commented
Didn't you veto adding more non-upstream directives before?

2024-03-12 13:33 UTC, lewis6991 commented
Hence the "PROTOTYPE" and "DO NOT MERGE" label.

2024-03-12 13:54 UTC, lewis6991 commented
What do you think though?

I think it's generic enough that any application should be able to easily implement it.

Bikeshed on the name?

2024-03-12 13:58 UTC, clason commented
In this case, I'd rather add (even) smarter default language resolution, to be honest. Or, conversely, a more generic directive that allows specifying how the node contents are used. (Not sure how that'd work, but I worry about proliferation of such twisty little directives, all alike...)

The name should indeed be changed, as this could also mean the _buffer_ filename (which is something tree-sitter-test wants).

2024-03-12 14:02 UTC, lewis6991 commented
> In this case, I'd rather add (even) smarter default language resolution, to be honest. Or, conversely, a more generic directive that allows specifying how the node contents are used. (Not sure how that'd work, but I worry about proliferation of such twisty little directives, all alike...)

Hmm, how do you mean `injection.language` should ideally point to a treesitter language name, and for explictness sake, I think we should use directives to get that language name.

Or do you mean just allow `injection.langage` to be a filename? I guess that could work, but personally I prefer something to flag this is a filename, not a lang.

2024-03-12 14:03 UTC, clason commented
> Or do you mean just allow injection.langage to be a filename? 

Yes. We already do this for filetype, after all.

2024-03-12 15:21 UTC, clason commented
Let's wait whether upstream wants to standardize that; then we can see how their version plays with Neovim's (much, _much_, more complex) filetype detection.

2024-03-27 12:08 UTC, clason requested changes
@lewis6991 I don't think we want another directive, but implementing `@injection.filename` to match Helix would make sense in my view. (Having two editors implement this consistently would put more pressure on upstream to make it official.)

2024-04-01 17:11 UTC, lewis6991 commented
Isn't `#set! injection.from <thing>` just `injection.<thing>` with extra steps? We can simply add `injection.shebang` if we want it. The grammar injections require a custom directive with or without this.

2024-04-01 17:11 UTC, closed without merging

2024-04-01 17:11 UTC, lewis6991 commented
Replaced with #28148

2024-04-01 17:12 UTC, clason commented
Yeah, `@injection.shebang` is also up for grabs but left as an exercise for the reader. (And I want to first see whether `tree-sitter` standardizes `@injection.filename`.