docs: mention builtin commenting in :h commentstring
neovim/neovim pull request #28220
Opened 2024-04-07 17:32 UTC by tom-anders

2024-04-07 17:34 UTC, tom-anders commented
(I took the liberty to assume that built-in commenting is probably more important than folding to the average user)

2024-04-07 17:40 UTC, tom-anders commented
@echasnovski FYI

2024-04-07 18:01 UTC, echasnovski requested changes
Nice catch! Should have been updated in original PR.

2024-04-07 18:01 UTC, echasnovski commented on src/nvim/options.lua
> +        Also used to add markers for folding, see |fold-marker|.
```suggestion
        comment text. For example, C uses "/*%s*/". Used for |commenting| and to
        add markers for folding, see |fold-marker|.
```

I think being as concise as possible is usually the goal in built-in docs.

2024-04-07 22:03 UTC, zeertzjq commented
Need to run `make doc` again

2024-04-08 08:12 UTC, dundargoc commented
Thank you for your contribution! We collect all typo fixes and similar small fixes into a single pull request and merge it once it gets big enough: https://github.com/neovim/neovim/pull/28208

2024-04-08 08:12 UTC, closed without merging