feat: command parsing recognizes visual range
neovim/neovim pull request #29207
Opened 2024-06-05 20:30 UTC by mg979

Problem: it's not possible to determine if a command is run over a visual range, rather than an ordinary range (line1, line2). Knowing we're handling a visual range is important, so that we can read the marks to know also the columns at which the range starts and ends.

Solution: introduce a `visualrange` boolean in the output of nvim_parse_cmd, and also pass it to lua callbacks for user commands, in the arguments table.

2024-06-05 20:51 UTC, mg979 commented
Or maybe it would be better to pass the range as string, so that the user can parse it? It would also cover `%`, `.` and empty string (that could be handled differently from `current line` that could be the default).

2024-06-05 22:33 UTC, zeertzjq requested changes, later dismissed
There may be whitespace before or inside the command address, and the Visual can also be indicated by `:*`, so this doesn't always work.

2024-06-05 22:42 UTC, zeertzjq requested changes
This is just a simple comparison, so why not just pass the full Ex command as another field to Lua user command callback instead of adding a special-cased field?

2024-06-06 01:51 UTC, mg979 commented
> This is just a simple comparison, so why not just pass the full Ex command as another field to Lua user command callbacks instead of adding a special-cased field for Visual range only?

Yes it makes more sense to pass the full command line. Or at least the part that comes before the command name, since the rest can be deduced from the rest (`args.name`, `args.fargs` etc). Moreover this would fail for more complex command lines that have other stuff before that range.

2024-06-06 01:51 UTC, closed without merging