fix(autocmds): prevent autocmds with once=true from calling itself
neovim/neovim pull request #29544
Opened 2024-07-02 21:33 UTC by Vinschers

Fix #25526.

Problem:
Autocmd with `once=true` that calls itself would enter a recursion loop since callback runs before aucmd's deletion.
The suggested fix does not work because deletion of autocmd breaks the reference needed in the callback function.

Solution:
Modify the aucmd's variable to have a NULL pattern. This makes it impossible to enter a recursion with once=true.
After callback, restore the original variable and continue to the regular deletion.

2024-07-03 13:11 UTC, ii14 requested changes

2024-07-03 13:11 UTC, ii14 commented on src/nvim/autocmd.c
> +    ac->pat = ac_copy.pat; // Restore aucmd reference
`ac` can be invalidated by the callback at this point, access through `kv_A(*acs, apc->auidx)`.

2024-07-03 18:11 UTC, ii14 approved these changes

2024-07-03 18:22 UTC, ii14 commented
Code has to be formatted though, run `make format`. I think it's just that there has to be two spaces between source code and inline comment.

2024-07-17 13:16 UTC, lewis6991 commented
Meaningful test failure:

```lua
 test/functional/lua/snippet_spec.lua @ 243: vim.snippet correctly indents with newlines
test/functional/testnvim.lua:127: EOF was received from Nvim. Likely the Nvim process crashed.

stack traceback:
	test/functional/testnvim.lua:127: in function 'exec_lua'
	test/functional/lua/snippet_spec.lua:35: in function 'test_expand_success'
	test/functional/lua/snippet_spec.lua:254: in function <test/functional/lua/snippet_spec.lua:243>
```

2024-10-09 11:22 UTC, justinmk commented
Looks reasonable, can you fix the test failure (seems like Nvim is crashing).

Please rebase to get updated CI.

2025-02-01 20:04 UTC, justinmk commented
Pushed a fixup.

2025-02-01 22:36 UTC, zeertzjq commented on test/functional/autocmd/autocmd_spec.lua
> +    eq(1, eval('g:count')) -- Added autocommands should not be executed
What is "Added autocommands"?

2025-02-01 22:38 UTC, justinmk commented on test/functional/autocmd/autocmd_spec.lua
> +    eq(1, eval('g:count')) -- Added autocommands should not be executed
that's a copy paste. i'll cleanup this test.

2025-02-01 23:13 UTC, zeertzjq commented on test/functional/autocmd/autocmd_spec.lua
> +      vim.g.count = 0
Why is `vim.g.count = 0` run twice?

2025-02-02 00:25 UTC, merged