'keywordprg' was set to `:help` twice in the vim ftplugin
neovim/neovim pull request #29857
Opened 2024-07-25 14:51 UTC by Futarimiti

I don't see a particular reason for this. Not observed in vim.

2024-07-25 14:54 UTC, clason commented
Probably happened mistakenly during porting runtime file updates.

2024-07-25 14:56 UTC, clason commented on runtime/ftplugin/vim.vim
>  setlocal keywordprg=:help
```suggestion
```
Please remove this and leave the other place to match the upstream ftplugin (helps prevent this cropping up again).

2024-07-25 23:27 UTC, zeertzjq requested changes

2024-07-25 23:27 UTC, zeertzjq commented on runtime/ftplugin/vim.vim
> -setlocal keywordprg=:help
Why are both instances removed?

2024-07-26 00:09 UTC, zeertzjq commented on runtime/ftplugin/vim.vim
> -setlocal keywordprg=:help
As mentioned above, you should keep this one and remove the one below.

2024-07-26 00:10 UTC, zeertzjq commented on runtime/ftplugin/vim.vim
> -setlocal keywordprg=:help
As mentioned above, you should keep this one and remove the one below.

2024-07-26 00:28 UTC, Futarimiti commented
@zeertzjq Does this look good to you?

2024-07-26 00:42 UTC, zeertzjq approved these changes

2024-07-26 00:45 UTC, merged