Color cmdline
neovim/neovim pull request #30406
Opened 2024-09-17 11:27 UTC by altermo

> [!Important]
> This PR requires another PR (https://github.com/neovim/neovim/pull/28412) to be merged before this one (though this dependency might change)
> Because of this, the full PR diff is not accurate, only look at the second commit for the true changes

This implements the logic of using treesitter to color the cmdline.

Questions to the maintainers:
+ Should `g:Nvim_color_cmdline` be replaced by a `vim._*` function?
+ In which file should the code live?

2024-09-17 13:37 UTC, clason requested changes

2024-09-17 13:37 UTC, clason commented on runtime/plugin/color_cmdline.lua
> +require 'vim.ui.cmdline'
If you do that, you might as well put everything in this file and cut out the middle man...

(Unless this is only temporary and for testing and you'll hook this up properly later.)

2024-09-17 13:39 UTC, clason commented on runtime/lua/vim/ui/cmdline.lua
> +vim._cmdline_highlighter = function(cmdline)
```suggestion
local M = {}
M.highlighter = function(cmdline)
```
It's already exposed as `vim._cmdline`.

2024-09-17 13:39 UTC, justinmk commented
btw, as a followup, it would be interesting to see if we could replace the internals of `nvim_parse_expression()` with a treesitter parser. Or at least deprecate it, and provide a documentation hint about how to use treesitter for parsing Vimscript expressions.

2024-09-17 13:42 UTC, luukvbaal commented
`g:Nvim_color_cmdline` and its underlying callback mechanism has been slated for removal since it was added in #6364. Promoting it now, after removal was reiterated in #26346 and #28412 seems odd to me.

I can't blame you or core for entertaining this while the default ext_ui plans lie on hold but getting rid of the parallel message grid path still seems more attractive to me.

2024-09-17 13:46 UTC, justinmk commented
> Promoting it now, after removal was reiterated in #26346 and #28412 seems odd to me.

@luukvbaal thanks for mentioning that. I forgot about that and/or didn't realize this was conflicting.

If this is conflicting with that work, then yes, let's wait on @luukvbaal 's work.

2024-11-16 23:13 UTC, justinmk requested changes
This should wait until (and may be canceled by) @luukvbaal 's work on the messages grid.

2025-05-02 09:03 UTC, justinmk commented
color cmdline implemented in https://github.com/neovim/neovim/pull/27855

2025-05-02 09:03 UTC, closed without merging