fix(float): missing error handle in win_alloc_aucmd_win
neovim/neovim pull request #30994
Opened 2024-10-30 11:50 UTC by glepnir

Problem: missng error handling of win_new_float in win_alloc_aucmd_win. and this function only used in autocmd.c so move it to autocmd.c with static.

Solution: handler err after calling win_new_float.

PS:  Is this a design that no error handling is needed here?  we assuming that the creation will always succeed then..not sure returning directly is okay. maybe need some data clean up..

2024-10-30 12:23 UTC, zeertzjq requested changes
No error can happen, and even if error can happen, it's much more complicated than a simple `return`, so it's better to just `abort()` on failure.

2024-10-31 08:41 UTC, zeertzjq commented on src/nvim/autocmd.c
> +static inline bool aucmd_win_alloc(int idx)
Why `inline`?

2024-10-31 08:46 UTC, glepnir commented on src/nvim/autocmd.c
> +static inline bool aucmd_win_alloc(int idx)
ops forget undo here.

2024-10-31 08:54 UTC, zeertzjq approved these changes

2024-10-31 08:55 UTC, zeertzjq commented
Thinking again, I don't think this should be merged.

2024-10-31 08:55 UTC, closed without merging