api: Establish API naming convention.
neovim/neovim pull request #5344
Opened 2016-09-15 12:19 UTC by justinmk

Since this is essentially "zero cost", given recent deprecation work, I took the opportunity to (I hope) add consistency without too much churn. Also stubbed a section in `doc/develop.txt` with some API naming guidelines.

Changes:

```
old name:                   new name:
--------------------------------------------------
nvim_name_to_color          nvim_get_color_by_name
nvim_get_current_buffer     nvim_get_current_buf
nvim_get_current_window     nvim_get_current_win
nvim_get_buffers            nvim_list_buf
nvim_get_tabpages           nvim_list_tabpage
nvim_get_windows            nvim_list_win
nvim_set_current_buffer     nvim_set_current_buf
nvim_set_current_window     nvim_set_current_win
nvim_change_directory       nvim_set_directory
nvim_tabpage_get_window     nvim_tabpage_get_win
nvim_tabpage_get_windows    nvim_tabpage_list_win
nvim_win_get_buffer         nvim_win_get_buf
```

2016-09-15 14:06 UTC, ZyX-I commented
`list_buf` and friends are rather ambigious. It looks like you are listing *one* buffer (i.e. listing something that is “inside” because otherwise this does not make sense), not like you are obtaining a list of all buffers. Such functions need plural, not singular.

2016-09-15 14:06 UTC, ZyX-I requested changes
`list_buf` and friends are rather ambigious. It looks like you are listing one buffer (i.e. listing something that is “inside” because otherwise this does not make sense), not like you are obtaining a list of all buffers. Such functions need plural, not singular.

2016-09-15 14:07 UTC, ZyX-I commented
Oh, fine crosses.

2016-09-15 14:07 UTC, ZyX-I approved these changes

2016-09-15 14:09 UTC, ZyX-I commented
And review message is not deletable or editable, as well as I can’t change “approve” back to “reject” right now. Not sure whether this will change after force-push.

2016-09-15 14:26 UTC, justinmk commented
If we use plurals then the "list" verb probably isn't needed , can just say "get_bufs". I'll push that change.

2016-09-15 14:43 UTC, ZyX-I commented
list is better for the cases when there is both plural and singular form (e.g. for listing windows in tab pages).

2016-09-15 15:47 UTC, bfredl commented on src/nvim/api/buffer.c
> +void nvim_buf_del_highlight(Buffer buffer,
IMHO this is wrong, this does not "delete" a highlight in the way you "delete" a specific key from a dict, rather it clears _all_ highlights of a source from a specified region of the file (typically the entire file).

(Also why is the "add single comment" button greyed out as if you are not supposed to use it? I get two emails every time someone does any "review" operation... Sorry OT)

2016-09-15 16:16 UTC, justinmk commented
@bfredl is the difference significant enough ?

2016-09-15 16:33 UTC, bfredl commented
It is not the same operation.  del will delete one specified object, or throw an error. `clear_highlight` will silently do nothing, if the file already is clear of highlights, or remove one or many highlights, whatever needed. The point of a convention is surely that the same/analogous operation has the same name, but different operations have different names.

2016-09-15 16:37 UTC, justinmk commented
Ok. But I didn't expect to limit "delete" to only one item. Just like "get" may take a query or parameters, and "set" may set many lines etc.

2016-09-15 16:42 UTC, jamessan commented
> But I didn't expect to limit "delete" to only one item.

But do you expect "delete" to fail if the specified item doesn't exist?  That's the crux of @bfredl's point, I think.

"clear" means "do whatever is needed, even nothing, to clear all related state".  "delete" means "get rid of these specific items".  If those items don't exist, that should be an error.

2016-09-15 16:42 UTC, bfredl commented
but `set_lines` you can still set some _specific_ set of lines. You can't delete one _or_ several specific highlights. `clear_highilght` referers to the intended result, the range/buffer is _clear_ of highlights (highlights may get deleted or may not get deleted, whatever needed) the same way you can clear a dict of all its keys, which is not the same as deleting many specific keys at once.

2016-09-15 17:14 UTC, justinmk commented
Ok

2016-09-15 19:19 UTC, justinmk commented
Made those changes. Also renamed `change_directory` to `set_current_dir` for parallel form with the other `set_current_*` functions.

2016-09-15 21:51 UTC, justinmk commented
UBSAN failure is a unrelated timing issue. If there are no objections I'll merge in the next day.

2016-09-16 07:02 UTC, bfredl commented on src/nvim/api/vim.c
> +void nvim_set_current_dir(String dir, Error *err)
Can be fixed in a later PR, but API users would expect to also have `nvim_get_current_dir`, by symmetry or something.

2016-09-16 07:07 UTC, bfredl commented
LGTM :+1:

2016-09-17 04:30 UTC, merged