Return -1 from jobstart when cmd is non executable instead of exception
neovim/neovim pull request #5671
Opened 2016-11-26 03:05 UTC by aaron-williamson

Addresses the issue here: https://github.com/neovim/neovim/issues/5465 and also specs the proper behavior.

2016-12-08 15:52 UTC, jamessan approved these changes

2016-12-10 16:02 UTC, justinmk commented on src/nvim/eval.c
>      // String is not executable
the comment is not relevant anymore

2016-12-10 16:04 UTC, justinmk commented on src/nvim/globals.h
> -EXTERN char_u e_jobexe[] INIT(= N_("E902: \"%s\" is not an executable"));
I guess we should remove the E902 cases from the `*.po` files.

2016-12-10 16:07 UTC, justinmk commented on test/functional/core/job_spec.lua
> +    eq(-1, rv)
I also added a check for `eq("", eval("v:errmsg"))` here.

2016-12-10 16:39 UTC, justinmk requested changes

2016-12-10 16:39 UTC, justinmk commented on src/nvim/eval.c
> +    rettv->vval.v_number = -1;  // Return -1 on non executable
jobstart() doc mentions:

```
Returns:
- 0 on invalid arguments or if the job table is full
- -1 if {cmd}[0] is not executable.
```

`tv_to_argv()` may fail for reasons other than non-executable, such as invalid arguments. So we need more granularity from `tv_to_argv()`.

2016-12-11 00:16 UTC, justinmk commented on src/nvim/eval.c
> +    rettv->vval.v_number = -1;  // Return -1 on non executable
Fixed in https://github.com/neovim/neovim/pull/5750

2016-12-11 00:38 UTC, justinmk commented
Merged in #5750. Thanks @aaron-williamson

2016-12-11 00:38 UTC, closed without merging