vim-patch:7.4.2266,7.4.2280,7.4.2291
neovim/neovim pull request #6231
Opened 2017-03-07 20:37 UTC by jbradaric

```
vim-patch:7.4.2266

Problem:    printf() test fails on Windows. "-inf" is not used.
Solution:   Check for Windows-specific values for "nan".  Add sign to "inf"
            when appropriate.
```
https://github.com/vim/vim/commit/9992237a3e791fbc0c1ebf743ece1b75e1488410

```
vim-patch:7.4.2280

Problem:    printf() doesn't handle infinity float values correctly.
Solution:   Add a table with possible infinity values. (Dominique Pelle)
```
https://github.com/vim/vim/commit/e999782e369999539a1783a7ebe4eadcc6da28a8

```
vim-patch:7.4.2291

Problem:    printf() handles floats wrong when there is a sign.
Solution:   Fix placing the sign.  Add tests. (Dominique Pelle)
```
https://github.com/vim/vim/commit/04186095346daa60e82e981dad114de2b641d672

2017-03-08 22:52 UTC, Shougo commented
https://github.com/neovim/neovim/pull/6222#issuecomment-284314376

I think 7.4.2221 is already included.

2017-03-21 10:09 UTC, justinmk commented
@ZyX-I Any comments on this?

2017-03-21 10:35 UTC, ZyX-I requested changes

2017-03-21 10:35 UTC, ZyX-I commented on src/nvim/strings.c
> +              str_arg_l = STRLEN(tmp);
`tmp` is now `char`, do not use upper-case macros. And never use `strcpy`.

Actually, with the current code you may still use `memmove()`, but in order not to make mistakes in the future `memmove()` could be used only if you move `tmp` and `str_arg_l` as return arguments to `void infinity_str(…)`.

2017-03-21 10:35 UTC, ZyX-I commented on src/nvim/strings.c
> +            if ((fmt_spec == 'f' || fmt_spec == 'F') && abs_f > 1.0e307) {
I think that this should be `isinf(f) || ((fmt_spec == 'f' || fmt_spec == 'F') && abs_f > 1.0e307)`. And `isinf(f)` branch below could be removed then.

2017-03-21 10:35 UTC, ZyX-I commented on src/nvim/strings.c
> +                STRCPY(tmp, ASCII_ISUPPER(fmt_spec) ? "NAN" : "nan");
`memmove()`.

2017-03-21 10:35 UTC, ZyX-I commented on src/nvim/strings.c
> +                  l += snprintf(format + l, sizeof(format) - 1, ".%d",
This is incorrect: you “shrink” format by `l` by using `format + l`, `sizeof(format) - 1` does not represent available room then. Should be `- l`.

2017-03-21 10:35 UTC, ZyX-I commented on src/nvim/strings.c
> +                str_arg_l = (size_t)snprintf(tmp, sizeof(tmp), format, f);
`str_arg_l` is already size_t. Remove cast.

2017-03-21 10:35 UTC, ZyX-I commented on src/nvim/strings.c
> +                int l = 1;
All places where `l` is used expect or are fine with `size_t`. So change `int` to `size_t`.

2017-03-21 10:35 UTC, ZyX-I commented on src/nvim/strings.c
> +                assert(l + 1 < (int)sizeof(format));
Remove cast.

2017-03-21 10:35 UTC, ZyX-I commented on src/nvim/strings.c
>              } else {
And I guess it would be better to move `isnan()` on this level of indentation: if I read correctly now it is

```C
if ((fmt_spec == 'f' || fmt_spec == 'F') && abs_f > 1.0e307) {
  // inf 1
} else {
  if (isnan(f)) {
    // nan
  } else if (isinf(f)) {
    // inf 2
  } else {
    // num
  }  // no code after this
}
```

I suggest

```C
if (isinf(f) || (strchr("fF", fmt_spec) != NULL && abs_f > 1.0e307)) {
  // inf
} else if (isnan(f)) {
  // nan
} else {
  // num
}
```

Diff should also be cleaner because that will not move levels of indentation of `if (precision_specified)`, etc.

2017-03-21 21:42 UTC, jbradaric commented on src/nvim/strings.c
> +                str_arg_l = (size_t)snprintf(tmp, sizeof(tmp), format, f);
The cast is needed here because `snprintf` returns an `int`, and `str_arg_l` is `size_t`. Without the cast we get a conversion warning.

2017-03-21 22:57 UTC, ZyX-I commented on src/nvim/strings.c
> +                str_arg_l = (size_t)snprintf(tmp, sizeof(tmp), format, f);
OK, forgot the thing.

2017-03-21 23:00 UTC, ZyX-I approved these changes

2017-03-21 23:29 UTC, merged

2017-03-21 23:59 UTC, jszakmeister commented
This PR ended up reverting c6b3975774b21461873c6be9da3b9b0bcef4017a and re-introducing the conversion error problem again. :-(

2017-03-22 00:02 UTC, justinmk commented
Seems like QB didn't run on the latest version of this. Thanks for the note.

2017-03-22 00:03 UTC, ZyX-I commented
When fixing again it is better leave comment from that commit near the code it fixes.

2017-03-22 00:29 UTC, jszakmeister commented
@justinmk Yeah... it appears the build got stuck somehow... I'm not sure what it was waiting for, the processes in question were killed so it should've aborted. :-(

@ZyX-I I'm not sure I understand what you're saying.  There was no comment in the original commit.  Are you asking that when it is fixed again for them to leave a comment saying why it's there?  I don't think the change was removed as part of the code review, just probably missed when rebasing and a conflict emerged.  I could be wrong though.

2017-03-22 00:39 UTC, ZyX-I commented
@jszakmeister Each commit has commit comment. I did not mean comment from source code, I meant that you explained the change in git commit comment, but because I did not see that commit and did not see any problems with the code and neither did the @jbradaric the problem was reintroduced. That would not happen if comment from git was in source code.

BTW, “as are the literals” part is incorrect: C99 explicitly says that character constants have type `int` (6.4.4.4, p.10). Just modern compiler versions are smart enough not to bother programmers with such pointless warnings.

2017-03-22 01:18 UTC, jszakmeister commented
> @jszakmeister Each commit has commit comment. I did not mean comment from source code, I meant that you explained the change in git commit comment, but because I did not see that commit and did not see any problems with the code and neither did the @jbradaric the problem was reintroduced. That would not happen if comment from git was in source code.

I'd call it a commit message rather than a commit comment.  But you're confirming what I said above: you would have liked to see a comment in the source code for the change.  Personally, I thought it was too small to really comment on. *shrug*

> BTW, “as are the literals” part is incorrect: C99 explicitly says that character constants have type int (6.4.4.4, p.10). Just modern compiler versions are smart enough not to bother programmers with such pointless warnings.

By the letter of the law, you're absolutely right.  What I meant was that the literal can be represented quite well as a character--hence there's no real conversion error.  It's really a false positive in that sense.