[RFC] Add ‘eob’ option to fillchars
neovim/neovim pull request #6351
Opened 2017-03-24 15:51 UTC by FriedSock

This option allows configuring what character is shown on the empty
lines at the end of a buffer, previously hardcoded to ‘~’

Fixes: https://github.com/neovim/neovim/issues/4181

2017-03-24 15:53 UTC, justinmk commented on test/functional/options/fillchars_spec.lua
> +if helpers.pending_win32(pending) then return end
This should work just fine on Windows.

2017-03-24 15:54 UTC, justinmk commented on test/functional/options/fillchars_spec.lua
> +  describe('the "eob" option', function()
describe('"eob" flag', function()

2017-03-24 15:54 UTC, FriedSock commented
I noticed a mistake in the documentation/implementation whilst doing this PR. The docs for `'fillchars'` state:
```
	Characters to fill the statuslines and vertical separators.
	It is a comma separated list of items:

	  item		default		Used for ~
	  stl:c		' ' or '^'	statusline of the current window
	  stlnc:c	' ' or '='	statusline of the non-current windows
	  vert:c	'|'		vertical separators |:vsplit|
	  fold:c	'-'		filling 'foldtext'
	  diff:c	'-'		deleted lines of the 'diff' option
	  eob:c		'~'		empty lines at the end of a buffer

	*Any one that is omitted will fall back to the default.  For "stl" and
	"stlnc" the space will be used when there is highlighting, '^' or '='
	otherwise.*
```

However, if one of the items is missing, it will not fall back to the default. This behaviour also exists in vim 7.

2017-03-24 15:55 UTC, justinmk commented on test/functional/options/fillchars_spec.lua
> +      execute('set fillchars+=eob:\\ ')
how about trying some other characters? Including multibyte characters, if those are supported.

2017-03-24 15:56 UTC, justinmk commented on test/functional/options/fillchars_spec.lua
> +      execute('set fillchars+=eob:\\ ')
what happens if it's set to empty string?

2017-03-24 15:56 UTC, justinmk commented
LGTM after comments. Seems easy enough.

2017-03-24 16:00 UTC, jamessan commented
Thanks for working on this @FriedSock.  I would highly recommend submitting this patch upstream, as well.

2017-03-24 16:20 UTC, FriedSock commented on test/functional/options/fillchars_spec.lua
> +      execute('set fillchars+=eob:\\ ')
multibyte chars aren't supported, neither is setting anything in fillchars to empty string.

2017-03-24 16:31 UTC, bfredl commented on test/functional/options/fillchars_spec.lua
> +      execute('set fillchars+=eob:\\ ')
multibyte chars seem to work fine (maybe you meant composing chars won't)

2017-03-24 16:44 UTC, FriedSock commented on test/functional/options/fillchars_spec.lua
> +      execute('set fillchars+=eob:\\ ')
Ah yes sorry, I mistakenly tried this with multiple characters. Have added a multibyte character test case now.

2017-03-30 02:27 UTC, justinmk commented
- I don't think it works with multibyte characters, actually. E.g., try this: `Ｘ`
    - `:help 'listchars'` but `:help 'fillchars'` suggests only "stl" and "stlnc" flags must be single-byte. 
    - Probably `win_draw_end()` needs to be fixed.
- Need a note in `vim_diff.txt`, see the 'cpoptions' line for example.

2017-03-30 05:33 UTC, ZyX-I requested changes

2017-03-30 05:33 UTC, ZyX-I commented on test/functional/options/fillchars_spec.lua
> +      ]])
I would suggest also checking fullwidth (e.g. U+FF21), composing (both `a`+U+0340 and just U+0340), invalid unicode (`let &fillchars="eob:\x80"`), control characters (`let &fillchars="eob:\n"`), Unicode control characters (`let &fillchars="eob:\u0094"`), just two characters (`ab`). Note: I am not suggesting that all of this must work. Checking errors is also needed. Especially interesting just U+0340: try using `let &fillchars="diff:\u0340"` and running a diff, result is weird.

2017-03-30 05:35 UTC, ZyX-I requested changes

2017-03-30 05:35 UTC, ZyX-I commented on test/functional/options/fillchars_spec.lua
> +      ]])
And missing test for empty fillchars, especially empty after successfully setting to something non-standard.

2018-06-13 13:52 UTC, LeOtaku commented
Any reason this has been delayed for so long? What is preventing this from being pushed forward?

2018-06-13 14:03 UTC, KillTheMule commented
The author hasn't been active for some time. Someone needs to pick this up and finish it.

2018-06-13 15:46 UTC, bfredl commented
I might be looking into this. I will also consider converting fillchars to schar_T (#7992) representation which maybe makes the code simpler and will allow composing chars as fillchars (mostly because why not), though if this is too messy in a separate PR.

2018-06-13 16:39 UTC, bfredl commented
Rebased as #8546

2018-06-14 12:03 UTC, justinmk commented
Closed by https://github.com/neovim/neovim/pull/8546

2018-06-14 12:03 UTC, closed without merging