Fix hard-coded Python paths in CheckHealth.
neovim/neovim pull request #6714
Opened 2017-05-10 13:35 UTC by vext01

I've tested the Python provider path, but not the curl one (please check).

Before:
```
## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2.7 in the environment.
  - INFO: Executable: /usr/local/bin/python2.7
  - ERROR: Command error -1: python -c from neovim import VERSION as v; print("{}.{}.{}{}".format(v.major, v.minor, v.patch, v.prerelease))
  - INFO: Python2 version: 2.7.13
  - INFO: python2.7-neovim version: 0.1.13
  - SUCCESS: Latest python2.7-neovim is installed: 0.1.13
```

After:
```
## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2.7 in the environment.
  - INFO: Executable: /usr/local/bin/python2.7
  - INFO: Python2 version: 2.7.13
  - INFO: python2.7-neovim version: 0.1.13
  - SUCCESS: Latest python2.7-neovim is installed: 0.1.13
```

Thanks

2017-05-10 13:41 UTC, justinmk requested changes

2017-05-10 13:41 UTC, justinmk commented on runtime/autoload/health/provider.vim
> +  elseif executable(a:python)
Parameter needs to be added and passed

2017-05-10 13:48 UTC, vext01 commented on runtime/autoload/health/provider.vim
> +  elseif executable(a:python)
Sorry, I'm not sure what you mean. (I don't really know vimscript)

2017-05-10 13:53 UTC, vext01 commented on runtime/autoload/health/provider.vim
> +  elseif executable(a:python)
oh, i see, one moment.

2017-05-10 13:57 UTC, vext01 commented on runtime/autoload/health/provider.vim
> +  elseif executable(a:python)
Actually, that's quite annoying to pass around, isn't it?

2017-05-10 14:13 UTC, ZyX-I requested changes

2017-05-10 14:13 UTC, ZyX-I commented on runtime/autoload/health/provider.vim
> +          \ ? a:python + 'urllib.request error: '.s:shell_error
VimL is not using `+` for concatenation.

2017-05-10 20:08 UTC, brcolow commented on runtime/autoload/health/provider.vim
> +          \ ? a:python + 'urllib.request error: '.s:shell_error
(It uses a dot, or period, for string concat)

2017-05-10 20:17 UTC, justinmk commented
Going to fix/merge this now

2017-05-11 11:00 UTC, justinmk commented on runtime/autoload/health/provider.vim
> +  elseif executable(a:python)
Actually, I reverted this change. `curl` is the main expectation, `python` is a fallback. This is only a download utility, not related to general python env sniffing.

2017-05-11 12:51 UTC, justinmk commented
merged

2017-05-11 12:51 UTC, closed without merging