[RDY] vim-patch:8.0.0142
neovim/neovim pull request #7335
Opened 2017-09-28 14:32 UTC by ckelsel

Problem:    Normal colors are wrong with 'termguicolors'.
Solution:   Initialize to INVALCOLOR instead of zero. (Ben Jackson, closes
            vim/vim#1344)

https://github.com/vim/vim/commit/0cdb72aa38c4a0140c94d56bf8bc17cb30260ebf

2017-09-29 05:21 UTC, justinmk commented
Can someone test this?

2017-09-29 06:24 UTC, KillTheMule commented
Steps are laid out in https://github.com/vim/vim/issues/1343, I'd give it a shot if no one else wants to.

2017-09-29 07:49 UTC, teto commented
I've had a bunch of similar error I fixed in my hilights-related PR ; https://github.com/neovim/neovim/pull/7082  and subsequent. It might or not fix this already.

2017-09-29 18:49 UTC, KillTheMule commented
I can't reproduce what's described in https://github.com/vim/vim/issues/1343#issuecomment-269716376, neither in vim (I downloaded 8.0.0141 for the test), nor in nvim. Also the corresponding test does not show a change when run on master vs. run with this PR. You can see the test at https://github.com/KillTheMule/neovim/commit/01fcdbd84d54f6af84f8f21392b8153172582758.

Not sure how to proceed when I can't reproduce the issue.

2017-09-29 19:58 UTC, jamessan commented
> Ok I could reproduce with vim 8.0.0134, but still not with nvim.

Yes, nvim behaves differently than vim.  It behaves like gvim does in this case.  However, IMHO, both nvim and gvim are wrong.  They show (bold?) white text on a white background.  The background should be black.

2017-09-29 19:59 UTC, KillTheMule commented
It's not black, it's grey right? That's the cursorline, if I'm not mistaken.

2017-09-29 20:02 UTC, jamessan commented
> It's not black, it's grey right?

Ah, you're right.  nvim and gvim set `guibg` to `Grey90` for `CursorLine`, while vim sets it to `Grey40`.

2017-09-29 20:07 UTC, jamessan commented
> nvim and gvim set guibg to Grey90 for CursorLine, while vim sets it to Grey40.

Which is due to differences in the value for `'background'`.  `background=dark` sets `Grey40`, `background=light` sets `Grey90`.  gvim, and apparently nvim, default to light and vim defaults to dark.

2017-09-29 20:48 UTC, bfredl commented on src/nvim/syntax.c
> +    new_en.rgb_fg_color = -1;
Alternatively, maybe this entire branch can be removed? `new_en` already has the correct `ATTRENTRY_INIT` value before the `memset()`.

2017-10-07 10:50 UTC, justinmk requested changes
see comments

2017-10-07 14:42 UTC, ckelsel commented
Fixed.

2017-10-07 15:12 UTC, justinmk approved these changes

2017-10-07 15:20 UTC, merged